"""Odometry and waypoint execution loop for Navigation."""

from __future__ import annotations

import math
import logging
import time
from typing import Any

from nav.mission.model.geometry import distance_xy, point_summary
from nav.mission.model.state import MissionEvent, MissionMode, MissionState
from nav.mission.tracking.waypoint_tracker import (
    EV_PATH_COMPLETE,
    EV_STUCK,
    EV_STUCK_WARN,
    EV_WAYPOINT_REACHED,
)
from runtime.msgs.geometry import Pose, PoseStamped, Quaternion, Vector3
from runtime.msgs.nav import Odometry
from runtime.msgs.numpy_compat import np

logger = logging.getLogger(__name__)


class NavigationExecutionMixin:
    def _start_external_strategy_path(self, goals: list[np.ndarray]) -> None:
        """Execute an externally planned strategy path through LingTu tracking."""
        try:
            path = self._validate_planned_path(goals)
            path = self._reanchor_external_strategy_path(path)
        except RuntimeError as exc:
            self._failure_reason = f"invalid external strategy path: {exc}"
            self._tracker.clear()
            self._publish_motion_stop()
            self._apply_event(
                MissionEvent.PLAN_FAILED,
                reason=self._failure_reason,
            )
            return
        if len(path) < 2:
            self.adapter_status.publish({
                "event": "external_strategy_path_ignored",
                "reason": "path_too_short",
                "points": len(path),
                "ts": time.time(),
            })
            return

        self._using_external_strategy_path = True
        self._clear_partial_goal_progress()
        self._goal = np.asarray(path[-1][:3], dtype=float).copy()
        self._goal_frame_id = self._planning_frame_id
        self._active_path_terminal_goal = self._goal.copy()
        self._active_external_strategy_path = [
            np.asarray(point[:3], dtype=float).copy() for point in path
        ]
        self._failure_reason = ""
        self._direct_goal_fallback_status = None
        self._mission_start_time = time.time()
        self._last_costmap_replan_time = time.time()
        self._set_replan_count(0)

        self._tracker.reset(path, self._robot_pos, self._robot_yaw)
        self._tracker.update(self._robot_pos, self._robot_yaw)
        if self._tracker.current_waypoint is None:
            self.adapter_status.publish({
                "event": "external_strategy_path_ignored",
                "reason": "already_complete",
                "points": len(path),
                "ts": time.time(),
            })
            return

        self._apply_event(
            MissionEvent.EXTERNAL_PATH_ACCEPTED,
            reason="external path accepted",
        )
        self._publish_global_path(path)
        self._apply_event(MissionEvent.PLAN_OK, reason="external path ready")
        self.adapter_status.publish({
            "event": "external_strategy_path_control",
            "points": len(path),
            "goal": point_summary(self._goal),
            "current_waypoint": point_summary(self._tracker.current_waypoint),
            "ts": time.time(),
        })
        self._publish_waypoint()

    def _reanchor_external_strategy_path(
        self,
        path: list[np.ndarray],
    ) -> list[np.ndarray]:
        """Return the forward path segment anchored near current odometry.

        External strategy paths are generated by another ROS graph. Before
        tracking them directly, require at least one path point near the
        current robot pose and start tracking from that segment.
        """
        if len(path) < 2:
            raise RuntimeError("path_too_short")
        robot = np.asarray(self._robot_pos[:3], dtype=float)
        if not np.all(np.isfinite(robot[:2])):
            raise RuntimeError("missing_current_odometry")
        distances = [
            float(np.linalg.norm(np.asarray(point[:2], dtype=float) - robot[:2]))
            for point in path
        ]
        nearest_index = min(range(len(distances)), key=distances.__getitem__)
        nearest_distance = distances[nearest_index]
        if nearest_distance > max(0.0, self._external_strategy_start_tolerance_m):
            raise RuntimeError(
                "path_not_anchored_near_current_odom "
                f"(nearest={nearest_distance:.2f}m)"
            )
        anchored = [np.asarray(point[:3], dtype=float).copy() for point in path[nearest_index:]]
        if len(anchored) < 2:
            raise RuntimeError("path_has_no_forward_segment_after_odom_anchor")
        if float(np.linalg.norm(anchored[0][:2] - robot[:2])) > 0.05:
            anchored.insert(0, robot.copy())
        return anchored

    def _on_odom(self, odom: Odometry) -> None:
        self._odom_frame_id = str(getattr(odom, "frame_id", "") or "unknown")
        self._frame_contract.report_frame_mismatch("odometry", self._odom_frame_id)
        if self._frame_contract.is_frame_mismatch(self._odom_frame_id, source="odometry"):
            if self._frame_contract.has_motion_artifacts(
                self._get_state(), self._tracker.path_length, self._goal, self._patrol_goals,
            ):
                self._block_for_frame_mismatch("odometry", self._odom_frame_id)
            return
        raw_yaw: float | None = None
        try:
            raw_yaw = float(odom.yaw)
            if not math.isfinite(raw_yaw):
                raw_yaw = None
        except (AttributeError, TypeError, ValueError):
            raw_yaw = None
        robot_pos, robot_yaw = self._odom_pose_in_planning_frame(odom, raw_yaw)
        self._robot_pos = robot_pos
        if robot_yaw is not None and math.isfinite(robot_yaw):
            self._robot_yaw = robot_yaw

        if self._paused_for_localization:
            return

        if not self._is_path_execution_state():
            return

        self._accelerate_stuck_check_on_reverse_motion(odom)
        status = self._tracker.update(self._robot_pos, self._robot_yaw)

        if status.event == EV_PATH_COMPLETE:
            self._handle_path_complete()
            return

        proximity_status = self._goal_proximity_path_complete_status()
        if proximity_status.get("complete"):
            self.adapter_status.publish({
                "event": "goal_proximity_path_complete",
                "distance_to_goal_m": proximity_status.get("distance_to_goal_m"),
                "threshold_m": proximity_status.get("threshold_m"),
                "current_waypoint_distance_m": proximity_status.get(
                    "current_waypoint_distance_m"
                ),
                "waypoint_index": self._tracker.wp_index,
                "path_length": self._tracker.path_length,
                "goal": point_summary(self._goal),
                "ts": time.time(),
            })
            self._handle_path_complete()
            return

        elif status.event == EV_WAYPOINT_REACHED:
            self._apply_event(
                MissionEvent.WAYPOINT_REACHED,
                reason="waypoint reached",
            )
            self.adapter_status.publish({
                "event": "waypoint_reached",
                "index": status.wp_index,
                "total": status.wp_total,
            })
            self._publish_waypoint()

        elif status.event == EV_STUCK_WARN:
            self.adapter_status.publish({
                "event": "WARN_STUCK",
                "elapsed": round(time.time() - self._mission_start_time, 1),
            })

        elif status.event == EV_STUCK:
            if self._get_replan_count() < self._max_replan:
                self._set_replan_count(self._get_replan_count() + 1)
                self._apply_event(MissionEvent.STUCK, reason="stuck")
                if self._using_external_strategy_path:
                    self._execute_recovery_motion(post_action="external_strategy")
                else:
                    self._execute_recovery_motion(post_action="replan")
                return
            else:
                self._failure_reason = "stuck after max replans"
                self._apply_event(
                    MissionEvent.RECOVERY_FAILED,
                    reason=self._failure_reason,
                )

        self._check_mission_timeout()

    @staticmethod
    def _normalise_goal_proximity_completion_threshold(
        value: float | None,
        *,
        final_waypoint_threshold: float | None,
        waypoint_threshold: float,
    ) -> float:
        if value is None:
            value = (
                final_waypoint_threshold
                if final_waypoint_threshold is not None
                else waypoint_threshold
            )
        try:
            parsed = float(value)
        except (TypeError, ValueError):
            return 0.0
        if not math.isfinite(parsed) or parsed <= 0.0:
            return 0.0
        return parsed

    def _goal_proximity_path_complete_status(self) -> dict[str, Any]:
        if not self._complete_path_on_goal_proximity:
            return {"complete": False, "enabled": False}
        if self._goal is None or not self._tracker.has_path:
            return {"complete": False, "enabled": True}
        threshold = self._goal_proximity_completion_threshold
        if threshold <= 0.0:
            return {"complete": False, "enabled": True, "threshold_m": threshold}
        try:
            robot = np.asarray(self._robot_pos[:2], dtype=float)
            goal = np.asarray(self._goal[:2], dtype=float)
        except (TypeError, ValueError):
            return {"complete": False, "enabled": True, "threshold_m": threshold}
        if not (np.all(np.isfinite(robot)) and np.all(np.isfinite(goal))):
            return {"complete": False, "enabled": True, "threshold_m": threshold}
        goal_distance = float(np.linalg.norm(robot - goal))
        current_wp_distance: float | None = None
        current_wp = self._tracker.current_waypoint
        if current_wp is not None:
            try:
                current_wp_xy = np.asarray(current_wp[:2], dtype=float)
                if np.all(np.isfinite(current_wp_xy)):
                    current_wp_distance = float(np.linalg.norm(robot - current_wp_xy))
            except (TypeError, ValueError):
                current_wp_distance = None
        return {
            "complete": goal_distance <= threshold,
            "enabled": True,
            "distance_to_goal_m": round(goal_distance, 3),
            "threshold_m": round(float(threshold), 3),
            "current_waypoint_distance_m": (
                round(current_wp_distance, 3)
                if current_wp_distance is not None
                else None
            ),
        }

    def _handle_path_complete(self) -> None:
        if self._should_continue_after_partial_path():
            self.adapter_status.publish({
                "event": "partial_path_complete_replan",
                "goal": point_summary(self._goal),
                "path_terminal_goal": point_summary(
                    self._active_path_terminal_goal
                ),
                "distance_to_goal_m": distance_xy(
                    self._robot_pos,
                    self._goal,
                ),
                "ts": time.time(),
            })
            self._plan()
            return
        partial_status = self._partial_path_terminal_status()
        if (
            self._accept_partial_goal_progress
            and partial_status.get("partial")
        ):
            self._record_partial_goal_progress_complete()
            self.adapter_status.publish({
                "event": "partial_goal_progress_complete",
                "original_goal": point_summary(self._goal),
                "path_terminal_goal": point_summary(
                    self._active_path_terminal_goal
                ),
                "terminal_gap_m": partial_status.get("terminal_gap_m"),
                "distance_to_goal_m": partial_status.get("robot_gap_m"),
                "selected_planner": partial_status.get("selected_planner"),
                "reason": partial_status.get("reason"),
                "ts": time.time(),
            })
        if self._mission_mode == MissionMode.PATROL and self._patrol_goals:
            if self._advance_patrol():
                return
        self._publish_motion_stop()
        self._apply_event(MissionEvent.PATH_COMPLETE, reason="path complete")

    def _check_mission_timeout(self) -> None:
        # Mission timeout - only applies while mission is active
        if (self._is_path_execution_state()
                and self._mission_start_time > 0
                and time.time() - self._mission_start_time > self._mission_timeout):
            self._failure_reason = f"mission timeout ({self._mission_timeout}s)"
            self._tracker.clear()
            self._active_path_terminal_goal = None
            self._using_external_strategy_path = False
            self._active_external_strategy_path = []
            self._publish_motion_stop()
            self._apply_event(
                MissionEvent.PLAN_FAILED,
                reason=self._failure_reason,
            )
            logger.warning("Mission timeout after %.0fs", self._mission_timeout)

    def _on_traversability(self, msg: dict) -> None:
        """W2-8: update latest terrain class from nav.terrain."""
        if not isinstance(msg, dict):
            return
        klass = msg.get("traversability_class") or msg.get("class")
        if klass:
            self._latest_traversability_class = str(klass)

    def _publish_waypoint(self) -> None:
        wp = self._tracker.current_waypoint
        if wp is None:
            return
        pose = PoseStamped(
            pose=Pose(
                position=Vector3(
                    float(wp[0]), float(wp[1]),
                    float(wp[2]) if len(wp) > 2 else 0.0,
                ),
                orientation=Quaternion(0, 0, 0, 1),
            ),
            frame_id=self._planning_frame_id,
            ts=time.time(),
        )
        self.waypoint.publish(pose)
