# Generated by tools/generate_topic_contracts.py. Do not edit.
"""Typed views of the canonical runtime topic catalogue."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class RuntimeTopics:
    """Logical topic names used by Python runtime code."""

    added_obstacles: str = "/nav/added_obstacles"
    camera_color: str = "/camera/color/image_raw"
    camera_depth: str = "/camera/depth/image_raw"
    camera_info: str = "/camera/color/camera_info"
    check_obstacle: str = "/nav/check_obstacle"
    cloud_clearing: str = "/nav/cloud_clearing"
    cmd_vel: str = "/nav/cmd_vel"
    cumulative_map_cloud: str = "/slam/cumulative_map_cloud"
    driver_control_state: str = "/driver/control_state"
    driver_odometry: str = "/driver/odometry"
    exploration_ack: str = "/nav/exploration/ack"
    exploration_command: str = "/nav/exploration/command"
    exploration_execution_snapshot: str = "/nav/exploration_execution_snapshot"
    exploration_finish: str = "/exploration/finish"
    exploration_grid: str = "/nav/exploration_grid"
    exploration_local_path: str = "/exploration/local_path"
    exploration_run_event: str = "/nav/exploration/run/event"
    exploration_runtime: str = "/exploration/runtime"
    exploration_segment_ack: str = "/nav/exploration_segment/ack"
    exploration_segment_request: str = "/nav/exploration_segment/request"
    exploration_segment_status: str = "/nav/exploration_segment/status"
    exploration_snapshot: str = "/nav/exploration_snapshot"
    exploration_start: str = "/exploration/start"
    exploration_way_point: str = "/exploration/way_point"
    geofence_alert: str = "/nav/geofence/alert"
    geofence_command: str = "/nav/geofence/command"
    geofence_response: str = "/nav/geofence/response"
    global_path: str = "/nav/global_path"
    gnss_fix: str = "/gnss/fix"
    gnss_odom: str = "/gnss/odom"
    gnss_status: str = "/gnss/status"
    goal_point: str = "/nav/goal_point"
    height_rays: str = "/nav/height_rays"
    imu: str = "/imu/raw"
    inspection_evidence_request: str = "/nav/inspection/evidence/request"
    inspection_evidence_result: str = "/nav/inspection/evidence/result"
    inspection_status: str = "/nav/inspection/status"
    inspection_task_ack: str = "/nav/inspection/task/ack"
    inspection_task_event: str = "/nav/inspection/task/event"
    inspection_task_request: str = "/nav/inspection/task/request"
    lidar_scan: str = "/lidar/raw_frame"
    local_path: str = "/nav/local_path"
    local_planner_clear_path: str = "/nav/local_planner/clear_path"
    local_planner_control_hint: str = "/nav/local_planner/control_hint"
    local_traversability: str = "/nav/local_traversability"
    localization_health: str = "/slam/localization_health"
    localization_quality: str = "/slam/localization_quality"
    map_clearing: str = "/nav/map_clearing"
    map_cloud: str = "/slam/map_cloud"
    map_observation: str = "/slam/map_observation"
    maps_accumulated_cloud: str = "/maps/accumulated_cloud"
    maps_activation_ack: str = "/maps/activation/ack"
    maps_activation_request: str = "/maps/activation/request"
    maps_elevation: str = "/maps/elevation"
    maps_esdf: str = "/maps/esdf"
    maps_live_cloud: str = "/maps/live_cloud"
    maps_local_collision: str = "/maps/local_collision"
    maps_occupancy: str = "/maps/occupancy"
    maps_scene: str = "/maps/scene"
    maps_state: str = "/maps/state"
    maps_voxel_cloud: str = "/maps/voxel_cloud"
    nav_command_ack: str = "/nav/command/ack"
    nav_command_request: str = "/nav/command/request"
    nav_goal_status: str = "/nav/goal/status"
    nav_state: str = "/nav/state"
    nav_way_point: str = "/nav/way_point"
    navigation_boundary: str = "/nav/navigation_boundary"
    odom_prior: str = "/slam/odom_prior"
    odometry: str = "/slam/odometry"
    operator_motion_ack: str = "/nav/operator_motion/ack"
    operator_motion_control: str = "/nav/operator_motion/control"
    operator_motion_sample: str = "/nav/operator_motion/sample"
    operator_motion_status: str = "/nav/operator_motion/status"
    plan_request: str = "/nav/plan/request"
    plan_result: str = "/nav/plan/result"
    planner_status: str = "/nav/planner_status"
    raw_lidar_packet: str = "/lidar/raw_packet"
    registered_cloud: str = "/slam/registered_cloud"
    robot_joint_states: str = "/robot/joint_states"
    saved_map_cloud: str = "/slam/saved_map_cloud"
    semantic_instruction: str = "/nav/semantic/instruction"
    semantic_scene_graph: str = "/nav/semantic/scene_graph"
    semantic_view_request: str = "/nav/semantic/views/request"
    semantic_view_result: str = "/nav/semantic/views/result"
    sim_clock: str = "/sim/clock"
    sim_imu: str = "/sim/imu"
    sim_lidar_raw_frame: str = "/sim/lidar/raw_frame"
    sim_truth_odometry: str = "/sim/truth/odom"
    slam_map_snapshot_ack: str = "/slam/map_event"
    slam_map_snapshot_request: str = "/slam/map_command"
    slam_relocalization_request: str = "/slam/relocalization/request"
    slam_relocalization_response: str = "/slam/relocalization/response"
    state_estimation_at_scan: str = "/slam/state_at_scan"
    terrain_map: str = "/nav/terrain_map"
    terrain_map_ext: str = "/nav/terrain_map_ext"
    tf: str = "/tf"
    tf_static: str = "/tf_static"
    traversability: str = "/nav/traversability"


@dataclass(frozen=True, slots=True)
class TopicSpec:
    """Native DDS binding for one logical topic."""

    topic: str
    dds_topic: str
    message_type: str
    qos_profile: str

    @property
    def idl_type(self) -> str:
        return self.message_type

    @property
    def type_name(self) -> str:
        return self.message_type.rsplit(".", 1)[-1]


TOPICS = RuntimeTopics()

TOPIC_SPECS = {
    "/camera/color/image_raw": TopicSpec(
        "/camera/color/image_raw",
        "rt/camera/color",
        "lingtu.dds.Image",
        "CameraStream",
    ),
    "/camera/depth/image_raw": TopicSpec(
        "/camera/depth/image_raw",
        "rt/camera/depth",
        "lingtu.dds.Image",
        "CameraStream",
    ),
    "/camera/color/camera_info": TopicSpec(
        "/camera/color/camera_info",
        "rt/camera/info",
        "lingtu.dds.CameraInfo",
        "CameraInfo",
    ),
    "/nav/cloud_clearing": TopicSpec(
        "/nav/cloud_clearing",
        "rt/nav/cloud_clearing",
        "lingtu.dds.Bool",
        "ControlCommand",
    ),
    "/nav/cmd_vel": TopicSpec(
        "/nav/cmd_vel",
        "rt/nav/cmd_vel",
        "lingtu.dds.FinalVelocityCommand",
        "FinalVelocityCommand",
    ),
    "/slam/cumulative_map_cloud": TopicSpec(
        "/slam/cumulative_map_cloud",
        "rt/slam/cumulative_map_cloud",
        "lingtu.dds.PointCloud2",
        "LidarPointcloud",
    ),
    "/driver/control_state": TopicSpec(
        "/driver/control_state",
        "rt/driver/control_state",
        "lingtu.dds.DriverControlState",
        "SystemStatus",
    ),
    "/driver/odometry": TopicSpec(
        "/driver/odometry",
        "rt/driver/odometry",
        "lingtu.dds.Odometry",
        "HighFreqState",
    ),
    "/nav/exploration/ack": TopicSpec(
        "/nav/exploration/ack",
        "rt/nav/exploration/ack",
        "lingtu.dds.ExplorationCommandAck",
        "CommandAck",
    ),
    "/nav/exploration/command": TopicSpec(
        "/nav/exploration/command",
        "rt/nav/exploration/command",
        "lingtu.dds.ExplorationCommandRequest",
        "CommandRequest",
    ),
    "/nav/exploration_execution_snapshot": TopicSpec(
        "/nav/exploration_execution_snapshot",
        "rt/nav/exploration_execution_snapshot",
        "lingtu.dds.ExplorationExecutionGrid",
        "MapGrid",
    ),
    "/exploration/finish": TopicSpec(
        "/exploration/finish",
        "rt/exploration/finish",
        "lingtu.dds.Bool",
        "Event",
    ),
    "/nav/exploration_grid": TopicSpec(
        "/nav/exploration_grid",
        "rt/nav/exploration_grid",
        "lingtu.dds.OccupancyGrid",
        "MapGrid",
    ),
    "/exploration/local_path": TopicSpec(
        "/exploration/local_path",
        "rt/exploration/local_path",
        "lingtu.dds.Path",
        "Event",
    ),
    "/nav/exploration/run/event": TopicSpec(
        "/nav/exploration/run/event",
        "rt/nav/exploration/run/event",
        "lingtu.dds.ExplorationRunEvent",
        "TaskEvent",
    ),
    "/exploration/runtime": TopicSpec(
        "/exploration/runtime",
        "rt/exploration/runtime",
        "lingtu.dds.Float32",
        "Event",
    ),
    "/nav/exploration_segment/ack": TopicSpec(
        "/nav/exploration_segment/ack",
        "rt/nav/exploration_segment/ack",
        "lingtu.dds.ExplorationSegmentAck",
        "CommandAck",
    ),
    "/nav/exploration_segment/request": TopicSpec(
        "/nav/exploration_segment/request",
        "rt/nav/exploration_segment/request",
        "lingtu.dds.ExplorationSegmentRequest",
        "CommandRequest",
    ),
    "/nav/exploration_segment/status": TopicSpec(
        "/nav/exploration_segment/status",
        "rt/nav/exploration_segment/status",
        "lingtu.dds.ExplorationSegmentStatus",
        "CommandAck",
    ),
    "/nav/exploration_snapshot": TopicSpec(
        "/nav/exploration_snapshot",
        "rt/nav/exploration_snapshot",
        "lingtu.dds.ExplorationGrid",
        "MapGrid",
    ),
    "/exploration/start": TopicSpec(
        "/exploration/start",
        "rt/exploration/start",
        "lingtu.dds.Bool",
        "Event",
    ),
    "/exploration/way_point": TopicSpec(
        "/exploration/way_point",
        "rt/exploration/way_point",
        "lingtu.dds.PointStamped",
        "Event",
    ),
    "/nav/geofence/alert": TopicSpec(
        "/nav/geofence/alert",
        "rt/nav/geofence/alert",
        "lingtu.dds.GeofenceAlert",
        "SystemStatus",
    ),
    "/nav/geofence/command": TopicSpec(
        "/nav/geofence/command",
        "rt/nav/geofence/command",
        "lingtu.dds.GeofenceCommandRequest",
        "CommandRequest",
    ),
    "/nav/geofence/response": TopicSpec(
        "/nav/geofence/response",
        "rt/nav/geofence/response",
        "lingtu.dds.GeofenceCommandAck",
        "CommandAck",
    ),
    "/nav/global_path": TopicSpec(
        "/nav/global_path",
        "rt/nav/global_path",
        "lingtu.dds.Path",
        "GlobalPath",
    ),
    "/gnss/fix": TopicSpec(
        "/gnss/fix",
        "rt/gnss/fix",
        "lingtu.dds.GnssFix",
        "HighFreqState",
    ),
    "/gnss/odom": TopicSpec(
        "/gnss/odom",
        "rt/gnss/odom",
        "lingtu.dds.Odometry",
        "HighFreqState",
    ),
    "/gnss/status": TopicSpec(
        "/gnss/status",
        "rt/gnss/status",
        "lingtu.dds.GnssStatus",
        "SystemStatus",
    ),
    "/imu/raw": TopicSpec(
        "/imu/raw",
        "rt/imu/raw",
        "lingtu.dds.Imu",
        "SensorStream",
    ),
    "/nav/inspection/evidence/request": TopicSpec(
        "/nav/inspection/evidence/request",
        "rt/nav/inspection/evidence/request",
        "lingtu.dds.InspectionEvidenceRequest",
        "InspectionEvidence",
    ),
    "/nav/inspection/evidence/result": TopicSpec(
        "/nav/inspection/evidence/result",
        "rt/nav/inspection/evidence/result",
        "lingtu.dds.InspectionEvidenceResult",
        "InspectionEvidence",
    ),
    "/nav/inspection/status": TopicSpec(
        "/nav/inspection/status",
        "rt/nav/inspection/status",
        "lingtu.dds.InspectionStatus",
        "SystemStatus",
    ),
    "/nav/inspection/task/ack": TopicSpec(
        "/nav/inspection/task/ack",
        "rt/nav/inspection/task/ack",
        "lingtu.dds.InspectionTaskAck",
        "CommandAck",
    ),
    "/nav/inspection/task/event": TopicSpec(
        "/nav/inspection/task/event",
        "rt/nav/inspection/task/event",
        "lingtu.dds.InspectionTaskEvent",
        "TaskEvent",
    ),
    "/nav/inspection/task/request": TopicSpec(
        "/nav/inspection/task/request",
        "rt/nav/inspection/task/request",
        "lingtu.dds.InspectionTaskRequest",
        "CommandRequest",
    ),
    "/lidar/raw_frame": TopicSpec(
        "/lidar/raw_frame",
        "rt/lidar/raw_frame",
        "lingtu.dds.LivoxFrame",
        "RawLidarStream",
    ),
    "/nav/local_path": TopicSpec(
        "/nav/local_path",
        "rt/nav/local_path",
        "lingtu.dds.Path",
        "GlobalPath",
    ),
    "/nav/local_traversability": TopicSpec(
        "/nav/local_traversability",
        "rt/nav/local_traversability",
        "lingtu.dds.OccupancyGrid",
        "LocalRiskGrid",
    ),
    "/slam/localization_health": TopicSpec(
        "/slam/localization_health",
        "rt/slam/localization_health",
        "lingtu.dds.Text",
        "LocalizationHealth",
    ),
    "/slam/localization_quality": TopicSpec(
        "/slam/localization_quality",
        "rt/slam/localization_quality",
        "lingtu.dds.Float32",
        "HighFreqState",
    ),
    "/nav/map_clearing": TopicSpec(
        "/nav/map_clearing",
        "rt/nav/map_clearing",
        "lingtu.dds.Bool",
        "ControlCommand",
    ),
    "/slam/map_cloud": TopicSpec(
        "/slam/map_cloud",
        "rt/slam/map_cloud",
        "lingtu.dds.PointCloud2",
        "LidarPointcloud",
    ),
    "/slam/map_observation": TopicSpec(
        "/slam/map_observation",
        "rt/slam/map_observation",
        "lingtu.dds.MapObservation",
        "LidarPointcloud",
    ),
    "/maps/accumulated_cloud": TopicSpec(
        "/maps/accumulated_cloud",
        "rt/maps/accumulated_cloud",
        "lingtu.dds.MapCloudLayer",
        "MapCloud",
    ),
    "/maps/activation/ack": TopicSpec(
        "/maps/activation/ack",
        "rt/maps/activation/ack",
        "lingtu.dds.MapActivationAck",
        "CommandAck",
    ),
    "/maps/activation/request": TopicSpec(
        "/maps/activation/request",
        "rt/maps/activation/request",
        "lingtu.dds.MapActivationRequest",
        "CommandRequest",
    ),
    "/maps/elevation": TopicSpec(
        "/maps/elevation",
        "rt/maps/elevation",
        "lingtu.dds.MapGrid",
        "MapGrid",
    ),
    "/maps/esdf": TopicSpec(
        "/maps/esdf",
        "rt/maps/esdf",
        "lingtu.dds.MapGrid",
        "MapGrid",
    ),
    "/maps/live_cloud": TopicSpec(
        "/maps/live_cloud",
        "rt/maps/live_cloud",
        "lingtu.dds.MapCloudLayer",
        "MapCloud",
    ),
    "/maps/local_collision": TopicSpec(
        "/maps/local_collision",
        "rt/maps/local_collision",
        "lingtu.dds.MapCollisionLayer",
        "LocalRiskGrid",
    ),
    "/maps/occupancy": TopicSpec(
        "/maps/occupancy",
        "rt/maps/occupancy",
        "lingtu.dds.MapGrid",
        "MapGrid",
    ),
    "/maps/scene": TopicSpec(
        "/maps/scene",
        "rt/maps/scene",
        "lingtu.dds.MapScene",
        "MapScene",
    ),
    "/maps/state": TopicSpec(
        "/maps/state",
        "rt/maps/state",
        "lingtu.dds.MapRuntimeState",
        "SystemStatus",
    ),
    "/maps/voxel_cloud": TopicSpec(
        "/maps/voxel_cloud",
        "rt/maps/voxel_cloud",
        "lingtu.dds.MapCloudLayer",
        "MapCloud",
    ),
    "/nav/command/ack": TopicSpec(
        "/nav/command/ack",
        "rt/nav/command/ack",
        "lingtu.dds.NavigationCommandAck",
        "CommandAck",
    ),
    "/nav/command/request": TopicSpec(
        "/nav/command/request",
        "rt/nav/command/request",
        "lingtu.dds.NavigationCommandRequest",
        "CommandRequest",
    ),
    "/nav/goal/status": TopicSpec(
        "/nav/goal/status",
        "rt/nav/goal/status",
        "lingtu.dds.NavigationGoalStatus",
        "CommandAck",
    ),
    "/nav/state": TopicSpec(
        "/nav/state",
        "rt/nav/state",
        "lingtu.dds.NavigationState",
        "SystemStatus",
    ),
    "/nav/way_point": TopicSpec(
        "/nav/way_point",
        "rt/nav/way_point",
        "lingtu.dds.PoseStamped",
        "ControlCommand",
    ),
    "/slam/odom_prior": TopicSpec(
        "/slam/odom_prior",
        "rt/slam/odom_prior",
        "lingtu.dds.Odometry",
        "SensorStream",
    ),
    "/slam/odometry": TopicSpec(
        "/slam/odometry",
        "rt/slam/odometry",
        "lingtu.dds.Odometry",
        "HighFreqState",
    ),
    "/nav/operator_motion/ack": TopicSpec(
        "/nav/operator_motion/ack",
        "rt/nav/operator_motion/ack",
        "lingtu.dds.OperatorMotionAck",
        "OperatorMotionAck",
    ),
    "/nav/operator_motion/control": TopicSpec(
        "/nav/operator_motion/control",
        "rt/nav/operator_motion/control",
        "lingtu.dds.OperatorMotionControl",
        "OperatorMotionControl",
    ),
    "/nav/operator_motion/sample": TopicSpec(
        "/nav/operator_motion/sample",
        "rt/nav/operator_motion/sample",
        "lingtu.dds.OperatorMotionSample",
        "OperatorMotionSample",
    ),
    "/nav/operator_motion/status": TopicSpec(
        "/nav/operator_motion/status",
        "rt/nav/operator_motion/status",
        "lingtu.dds.OperatorMotionStatus",
        "OperatorMotionStatus",
    ),
    "/nav/plan/request": TopicSpec(
        "/nav/plan/request",
        "rt/nav/plan/request",
        "lingtu.dds.PlanRequest",
        "CommandRequest",
    ),
    "/nav/plan/result": TopicSpec(
        "/nav/plan/result",
        "rt/nav/plan/result",
        "lingtu.dds.PlanResult",
        "CommandRequest",
    ),
    "/lidar/raw_packet": TopicSpec(
        "/lidar/raw_packet",
        "rt/lidar/raw_packet",
        "lingtu.dds.LivoxFrame",
        "RawLidarStream",
    ),
    "/slam/registered_cloud": TopicSpec(
        "/slam/registered_cloud",
        "rt/slam/registered_cloud",
        "lingtu.dds.PointCloud2",
        "LidarPointcloud",
    ),
    "/robot/joint_states": TopicSpec(
        "/robot/joint_states",
        "rt/robot/joint_states",
        "lingtu.dds.JointState",
        "SensorStream",
    ),
    "/slam/saved_map_cloud": TopicSpec(
        "/slam/saved_map_cloud",
        "rt/slam/saved_map_cloud",
        "lingtu.dds.PointCloud2",
        "LidarPointcloud",
    ),
    "/nav/semantic/instruction": TopicSpec(
        "/nav/semantic/instruction",
        "rt/nav/semantic/instruction",
        "lingtu.dds.Text",
        "Event",
    ),
    "/nav/semantic/views/request": TopicSpec(
        "/nav/semantic/views/request",
        "rt/nav/semantic/views/request",
        "lingtu.dds.SemanticViewRequest",
        "CommandRequest",
    ),
    "/nav/semantic/views/result": TopicSpec(
        "/nav/semantic/views/result",
        "rt/nav/semantic/views/result",
        "lingtu.dds.SemanticViewResult",
        "CommandRequest",
    ),
    "/sim/clock": TopicSpec(
        "/sim/clock",
        "rt/sim/clock",
        "lingtu.dds.Time",
        "SensorStream",
    ),
    "/sim/imu": TopicSpec(
        "/sim/imu",
        "rt/sim/imu",
        "lingtu.dds.Imu",
        "Default",
    ),
    "/sim/lidar/raw_frame": TopicSpec(
        "/sim/lidar/raw_frame",
        "rt/sim/lidar/raw_frame",
        "lingtu.dds.LivoxFrame",
        "RawLidarStream",
    ),
    "/sim/truth/odom": TopicSpec(
        "/sim/truth/odom",
        "rt/sim/truth/odom",
        "lingtu.dds.Odometry",
        "Default",
    ),
    "/slam/map_event": TopicSpec(
        "/slam/map_event",
        "rt/slam/map_event",
        "lingtu.dds.SlamMapSnapshotAck",
        "CommandAck",
    ),
    "/slam/map_command": TopicSpec(
        "/slam/map_command",
        "rt/slam/map_command",
        "lingtu.dds.SlamMapSnapshotRequest",
        "CommandRequest",
    ),
    "/slam/relocalization/request": TopicSpec(
        "/slam/relocalization/request",
        "rt/slam/relocalization/request",
        "lingtu.dds.RelocalizationRequest",
        "CommandRequest",
    ),
    "/slam/relocalization/response": TopicSpec(
        "/slam/relocalization/response",
        "rt/slam/relocalization/response",
        "lingtu.dds.RelocalizationResponse",
        "CommandAck",
    ),
    "/slam/state_at_scan": TopicSpec(
        "/slam/state_at_scan",
        "rt/slam/state_at_scan",
        "lingtu.dds.Odometry",
        "HighFreqState",
    ),
    "/nav/terrain_map": TopicSpec(
        "/nav/terrain_map",
        "rt/nav/terrain_map",
        "lingtu.dds.PointCloud2",
        "LidarPointcloud",
    ),
    "/nav/terrain_map_ext": TopicSpec(
        "/nav/terrain_map_ext",
        "rt/nav/terrain_map_ext",
        "lingtu.dds.PointCloud2",
        "LidarPointcloud",
    ),
    "/tf": TopicSpec(
        "/tf",
        "rt/tf",
        "lingtu.dds.TFMessage",
        "TfDynamic",
    ),
    "/tf_static": TopicSpec(
        "/tf_static",
        "rt/tf_static",
        "lingtu.dds.TFMessage",
        "TfStatic",
    ),
    "/nav/traversability": TopicSpec(
        "/nav/traversability",
        "rt/nav/traversability",
        "lingtu.dds.OccupancyGrid",
        "MapGrid",
    ),
}


def topic_spec(topic: str) -> TopicSpec | None:
    """Return the DDS contract for one logical topic."""

    return TOPIC_SPECS.get(str(topic))


def dds_topic_name(topic: str) -> str:
    """Return the DDS wire name, falling back to the standard rt prefix."""

    name = str(topic)
    spec = TOPIC_SPECS.get(name)
    return spec.dds_topic if spec else ("rt" + name if name.startswith("/") else name)
