#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <limits>
#include <optional>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "dds/dds.h"
#include "lingtu/maps/mapd/activation.hpp"
#include "lingtu/maps/store.hpp"
#include "lingtu_slam.h"
#include "message/cpp/dds_qos_profiles.hpp"
#include "message/cpp/dds_topics.hpp"

#if defined(_WIN32)
#include <process.h>
#else
#include <unistd.h>
#endif

namespace {

using lingtu::maps::MapStore;
using lingtu::maps::MapStoreConfig;
using lingtu::maps::mapd::ActivationCoordinator;
using lingtu::maps::mapd::ActivationOperation;
using lingtu::maps::mapd::ActivationOperationName;
using lingtu::maps::mapd::ActivationRequest;
using lingtu::maps::mapd::ActivationResult;
using lingtu::maps::mapd::ArtifactIdentity;
using lingtu::maps::mapd::MapIdentity;

struct Options {
  ActivationOperation operation{ActivationOperation::kVerify};
  std::string operand;
  int domain_id{0};
  std::filesystem::path map_root;
  std::chrono::milliseconds timeout{5000};
  std::string caller{"product-control"};
  std::string request_id;
};

std::string EnvOr(const char *name, std::string fallback) {
  const char *value = std::getenv(name);
  return value == nullptr || value[0] == '\0' ? std::move(fallback) : std::string{value};
}

std::filesystem::path ResolveMapRoot() {
  const char *configured = std::getenv("NAV_MAP_DIR");
  if (configured != nullptr && configured[0] != '\0') {
    return std::filesystem::absolute(configured).lexically_normal();
  }
  const char *home = std::getenv("HOME");
  if (home == nullptr || home[0] == '\0') {
    home = std::getenv("USERPROFILE");
  }
  if (home == nullptr || home[0] == '\0') {
    return std::filesystem::absolute("maps").lexically_normal();
  }
  const auto base = std::filesystem::path(home) / "data";
  const auto nova = base / "nova" / "maps";
  if (std::filesystem::exists(nova)) {
    return nova.lexically_normal();
  }
  return (base / "lingtu" / "maps").lexically_normal();
}

std::string MakeRequestId() {
#if defined(_WIN32)
  const int process_id = _getpid();
#else
  const int process_id = getpid();
#endif
  const auto stamp = std::chrono::steady_clock::now().time_since_epoch().count();
  return "mapctl-" + std::to_string(process_id) + "-" + std::to_string(stamp);
}

int ParseInt(const std::string &value, const char *field) {
  std::size_t consumed = 0U;
  const long parsed = std::stol(value, &consumed);
  if (consumed != value.size() || parsed < std::numeric_limits<int>::min() ||
      parsed > std::numeric_limits<int>::max()) {
    throw std::invalid_argument(std::string(field) + " is invalid");
  }
  return static_cast<int>(parsed);
}

void PrintUsage() {
  std::cout << "lingtu-mapctl stage MAP_ID [options]\n"
            << "lingtu-mapctl verify ACTIVATION_TOKEN [options]\n"
            << "lingtu-mapctl restore ACTIVATION_TOKEN [options]\n"
            << "  --domain-id N       CycloneDDS domain id\n"
            << "  --map-root PATH     saved-map root used to read exact identities\n"
            << "  --timeout-ms N      matching ACK deadline (default 5000)\n"
            << "  --request-id ID     idempotency key (generated by default)\n"
            << "  --caller NAME       audit caller (default product-control)\n";
}

Options ParseOptions(int argc, char **argv) {
  if (argc >= 2 && (std::string{argv[1]} == "--help" || std::string{argv[1]} == "-h")) {
    PrintUsage();
    std::exit(0);
  }
  if (argc < 3) {
    throw std::invalid_argument("operation and operand are required");
  }
  Options options;
  const std::string operation = argv[1];
  if (operation == "stage") {
    options.operation = ActivationOperation::kStage;
  } else if (operation == "restore") {
    options.operation = ActivationOperation::kRestore;
  } else if (operation == "verify") {
    options.operation = ActivationOperation::kVerify;
  } else {
    throw std::invalid_argument("operation must be stage, restore, or verify");
  }
  options.operand = argv[2];
  options.domain_id = ParseInt(EnvOr("LINGTU_DDS_DOMAIN_ID", "0"), "LINGTU_DDS_DOMAIN_ID");
  options.map_root = ResolveMapRoot();
  options.request_id = MakeRequestId();
  for (int index = 3; index < argc; ++index) {
    const std::string argument = argv[index];
    const auto next = [&]() -> std::string {
      if (++index >= argc) {
        throw std::invalid_argument(argument + " requires a value");
      }
      return argv[index];
    };
    if (argument == "--domain-id") {
      options.domain_id = ParseInt(next(), "--domain-id");
    } else if (argument == "--map-root") {
      options.map_root = std::filesystem::absolute(next()).lexically_normal();
    } else if (argument == "--timeout-ms") {
      const int timeout = ParseInt(next(), "--timeout-ms");
      if (timeout <= 0) {
        throw std::invalid_argument("--timeout-ms must be positive");
      }
      options.timeout = std::chrono::milliseconds(timeout);
    } else if (argument == "--request-id") {
      options.request_id = next();
    } else if (argument == "--caller") {
      options.caller = next();
    } else if (argument == "--help" || argument == "-h") {
      PrintUsage();
      std::exit(0);
    } else {
      throw std::invalid_argument("unknown option: " + argument);
    }
  }
  if (options.request_id.empty() || options.caller.empty()) {
    throw std::invalid_argument("request-id and caller must not be empty");
  }
  return options;
}

void AppendU32(std::string *output, std::uint32_t value) {
  for (int shift = 24; shift >= 0; shift -= 8) {
    output->push_back(static_cast<char>((value >> shift) & 0xffU));
  }
}

void AppendString(std::string *output, const std::string &value) {
  if (value.size() > std::numeric_limits<std::uint32_t>::max()) {
    throw std::invalid_argument("activation token field is too large");
  }
  AppendU32(output, static_cast<std::uint32_t>(value.size()));
  output->append(value);
}

void AppendIdentity(std::string *output, const MapIdentity &identity) {
  output->push_back(identity.present ? '\x01' : '\x00');
  if (!identity.present) {
    return;
  }
  AppendString(output, identity.map_id);
  AppendString(output, identity.version_id);
  AppendString(output, identity.frame_id);
  AppendString(output, identity.map_dir);
  if (identity.artifacts.size() > std::numeric_limits<std::uint32_t>::max()) {
    throw std::invalid_argument("activation token has too many artifacts");
  }
  AppendU32(output, static_cast<std::uint32_t>(identity.artifacts.size()));
  for (const auto &artifact : identity.artifacts) {
    AppendString(output, artifact.type);
    AppendString(output, artifact.uri);
    AppendString(output, artifact.sha256);
  }
}

std::string Base64UrlEncode(const std::string &input) {
  constexpr char kAlphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
  std::string output;
  output.reserve((input.size() * 4U + 2U) / 3U);
  std::uint32_t buffer = 0U;
  int bits = 0;
  for (const unsigned char byte : input) {
    buffer = (buffer << 8U) | byte;
    bits += 8;
    while (bits >= 6) {
      bits -= 6;
      output.push_back(kAlphabet[(buffer >> bits) & 0x3fU]);
    }
  }
  if (bits > 0) {
    output.push_back(kAlphabet[(buffer << (6 - bits)) & 0x3fU]);
  }
  return output;
}

int Base64UrlValue(char value) {
  if (value >= 'A' && value <= 'Z')
    return value - 'A';
  if (value >= 'a' && value <= 'z')
    return value - 'a' + 26;
  if (value >= '0' && value <= '9')
    return value - '0' + 52;
  if (value == '-')
    return 62;
  if (value == '_')
    return 63;
  return -1;
}

std::string Base64UrlDecode(const std::string &input) {
  std::string output;
  output.reserve(input.size() * 3U / 4U);
  std::uint32_t buffer = 0U;
  int bits = 0;
  for (const char character : input) {
    const int value = Base64UrlValue(character);
    if (value < 0) {
      throw std::invalid_argument("activation token is not base64url");
    }
    buffer = (buffer << 6U) | static_cast<std::uint32_t>(value);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      output.push_back(static_cast<char>((buffer >> bits) & 0xffU));
    }
  }
  if (bits > 0 && (buffer & ((1U << bits) - 1U)) != 0U) {
    throw std::invalid_argument("activation token has non-zero padding");
  }
  return output;
}

std::uint32_t ReadU32(const std::string &input, std::size_t *offset) {
  if (*offset > input.size() || input.size() - *offset < 4U) {
    throw std::invalid_argument("activation token is truncated");
  }
  std::uint32_t value = 0U;
  for (int index = 0; index < 4; ++index) {
    value = (value << 8U) | static_cast<unsigned char>(input[(*offset)++]);
  }
  return value;
}

std::string ReadString(const std::string &input, std::size_t *offset) {
  constexpr std::uint32_t kMaxFieldBytes = 64U * 1024U;
  const std::uint32_t length = ReadU32(input, offset);
  if (length > kMaxFieldBytes || *offset > input.size() || input.size() - *offset < length) {
    throw std::invalid_argument("activation token string is invalid");
  }
  std::string value = input.substr(*offset, length);
  *offset += length;
  return value;
}

MapIdentity ReadIdentity(const std::string &input, std::size_t *offset) {
  if (*offset >= input.size()) {
    throw std::invalid_argument("activation token is truncated");
  }
  MapIdentity identity;
  const unsigned char present = static_cast<unsigned char>(input[(*offset)++]);
  if (present > 1U) {
    throw std::invalid_argument("activation token presence flag is invalid");
  }
  identity.present = present == 1U;
  if (!identity.present) {
    return identity;
  }
  identity.map_id = ReadString(input, offset);
  identity.version_id = ReadString(input, offset);
  identity.frame_id = ReadString(input, offset);
  identity.map_dir = ReadString(input, offset);
  const std::uint32_t count = ReadU32(input, offset);
  if (count > 32U) {
    throw std::invalid_argument("activation token has too many artifacts");
  }
  identity.artifacts.reserve(count);
  for (std::uint32_t index = 0U; index < count; ++index) {
    identity.artifacts.push_back(
        {ReadString(input, offset), ReadString(input, offset), ReadString(input, offset)});
  }
  return identity;
}

std::string EncodeActivationToken(const MapIdentity &target, const MapIdentity &previous) {
  std::string binary{"LTMAP1", 6U};
  AppendIdentity(&binary, target);
  AppendIdentity(&binary, previous);
  return "v1." + Base64UrlEncode(binary);
}

std::pair<MapIdentity, MapIdentity> DecodeActivationToken(const std::string &token) {
  if (token.rfind("v1.", 0U) != 0U) {
    throw std::invalid_argument("activation token version is unsupported");
  }
  const std::string binary = Base64UrlDecode(token.substr(3U));
  if (binary.size() < 6U || binary.compare(0U, 6U, "LTMAP1") != 0) {
    throw std::invalid_argument("activation token magic is invalid");
  }
  std::size_t offset = 6U;
  MapIdentity target = ReadIdentity(binary, &offset);
  MapIdentity previous = ReadIdentity(binary, &offset);
  if (offset != binary.size()) {
    throw std::invalid_argument("activation token has trailing data");
  }
  return {std::move(target), std::move(previous)};
}

lingtu_dds_MapActivationOperation EncodeOperation(ActivationOperation operation) {
  switch (operation) {
    case ActivationOperation::kStage:
      return lingtu_dds_MAP_ACTIVATION_STAGE;
    case ActivationOperation::kRestore:
      return lingtu_dds_MAP_ACTIVATION_RESTORE;
    case ActivationOperation::kVerify:
      return lingtu_dds_MAP_ACTIVATION_VERIFY;
  }
  return lingtu_dds_MAP_ACTIVATION_VERIFY;
}

ActivationOperation DecodeOperation(lingtu_dds_MapActivationOperation value) {
  switch (value) {
    case lingtu_dds_MAP_ACTIVATION_STAGE:
      return ActivationOperation::kStage;
    case lingtu_dds_MAP_ACTIVATION_RESTORE:
      return ActivationOperation::kRestore;
    case lingtu_dds_MAP_ACTIVATION_VERIFY:
      return ActivationOperation::kVerify;
  }
  throw std::runtime_error("mapd returned an invalid activation operation");
}

void FillIdentity(const MapIdentity &identity, lingtu_dds_MapIdentity *message,
                  std::vector<lingtu_dds_MapArtifactIdentity> *artifacts) {
  message->present = identity.present;
  message->map_id = const_cast<char *>(identity.map_id.c_str());
  message->version_id = const_cast<char *>(identity.version_id.c_str());
  message->frame_id = const_cast<char *>(identity.frame_id.c_str());
  message->map_dir = const_cast<char *>(identity.map_dir.c_str());
  artifacts->resize(identity.artifacts.size());
  for (std::size_t index = 0U; index < identity.artifacts.size(); ++index) {
    auto &output = (*artifacts)[index];
    const auto &input = identity.artifacts[index];
    output.type = const_cast<char *>(input.type.c_str());
    output.uri = const_cast<char *>(input.uri.c_str());
    output.sha256 = const_cast<char *>(input.sha256.c_str());
  }
  message->artifacts._maximum = static_cast<std::uint32_t>(artifacts->size());
  message->artifacts._length = static_cast<std::uint32_t>(artifacts->size());
  message->artifacts._buffer = artifacts->data();
  message->artifacts._release = false;
}

std::string CopyString(const char *value) {
  return value == nullptr ? std::string{} : std::string{value};
}

MapIdentity DecodeIdentity(const lingtu_dds_MapIdentity &message) {
  if (message.artifacts._maximum < message.artifacts._length || message.artifacts._length > 32U ||
      (message.artifacts._length > 0U && message.artifacts._buffer == nullptr)) {
    throw std::runtime_error("mapd returned a malformed map identity");
  }
  MapIdentity identity;
  identity.present = message.present;
  identity.map_id = CopyString(message.map_id);
  identity.version_id = CopyString(message.version_id);
  identity.frame_id = CopyString(message.frame_id);
  identity.map_dir = CopyString(message.map_dir);
  identity.artifacts.reserve(message.artifacts._length);
  for (std::uint32_t index = 0U; index < message.artifacts._length; ++index) {
    const auto &artifact = message.artifacts._buffer[index];
    identity.artifacts.push_back(
        {CopyString(artifact.type), CopyString(artifact.uri), CopyString(artifact.sha256)});
  }
  return identity;
}

dds_entity_t Checked(dds_return_t value, const char *action) {
  if (value < 0) {
    throw std::runtime_error(std::string(action) + ": " + dds_strretcode(-value));
  }
  return static_cast<dds_entity_t>(value);
}

ActivationResult CallMapd(int domain_id, const ActivationRequest &request,
                          std::chrono::milliseconds timeout) {
  const auto participant =
      Checked(dds_create_participant(domain_id, nullptr, nullptr), "dds_create_participant");
  struct ParticipantGuard {
    dds_entity_t value;
    ~ParticipantGuard() { dds_delete(value); }
  } guard{participant};
  const auto publisher =
      Checked(dds_create_publisher(participant, nullptr, nullptr), "dds_create_publisher");
  const auto subscriber =
      Checked(dds_create_subscriber(participant, nullptr, nullptr), "dds_create_subscriber");
  const auto request_topic = Checked(
      dds_create_topic(participant, &lingtu_dds_MapActivationRequest_desc,
                       lingtu::message::kMapsActivationRequest.dds_topic.data(), nullptr, nullptr),
      "dds_create_topic(request)");
  const auto ack_topic = Checked(
      dds_create_topic(participant, &lingtu_dds_MapActivationAck_desc,
                       lingtu::message::kMapsActivationAck.dds_topic.data(), nullptr, nullptr),
      "dds_create_topic(ack)");
  auto request_qos = lingtu::dds::make_qos(
      lingtu::dds::qos_for_topic(lingtu::message::kMapsActivationRequest.dds_topic));
  auto ack_qos = lingtu::dds::make_qos(
      lingtu::dds::qos_for_topic(lingtu::message::kMapsActivationAck.dds_topic));
  const auto writer =
      Checked(dds_create_writer(publisher, request_topic, request_qos.get(), nullptr),
              "dds_create_writer(request)");
  const auto reader = Checked(dds_create_reader(subscriber, ack_topic, ack_qos.get(), nullptr),
                              "dds_create_reader(ack)");

  lingtu_dds_MapActivationRequest message{};
  message.request_id = const_cast<char *>(request.request_id.c_str());
  message.operation = EncodeOperation(request.operation);
  std::vector<lingtu_dds_MapArtifactIdentity> target_artifacts;
  std::vector<lingtu_dds_MapArtifactIdentity> previous_artifacts;
  FillIdentity(request.target, &message.target, &target_artifacts);
  FillIdentity(request.previous, &message.previous, &previous_artifacts);
  message.caller = const_cast<char *>(request.caller.c_str());
  message.reason = const_cast<char *>(request.reason.c_str());

  const auto deadline = std::chrono::steady_clock::now() + timeout;
  auto next_write = std::chrono::steady_clock::now();
  while (std::chrono::steady_clock::now() < deadline) {
    const auto now = std::chrono::steady_clock::now();
    if (now >= next_write) {
      Checked(dds_write(writer, &message), "dds_write(request)");
      next_write = now + std::chrono::milliseconds(500);
    }
    void *sample = dds_alloc(sizeof(lingtu_dds_MapActivationAck));
    std::memset(sample, 0, sizeof(lingtu_dds_MapActivationAck));
    void *samples[1] = {sample};
    dds_sample_info_t info{};
    const dds_return_t count = dds_take(reader, samples, &info, 1U, 1U);
    if (count < 0) {
      dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
      Checked(count, "dds_take(ack)");
    }
    if (count == 1 && info.valid_data) {
      const auto *ack = static_cast<lingtu_dds_MapActivationAck *>(sample);
      if (CopyString(ack->request_id) == request.request_id) {
        ActivationResult result;
        result.request_id = request.request_id;
        result.operation = DecodeOperation(ack->operation);
        result.accepted = ack->accepted;
        result.message = CopyString(ack->message);
        result.changed = ack->changed;
        result.target = DecodeIdentity(ack->target);
        result.previous = DecodeIdentity(ack->previous);
        result.active = DecodeIdentity(ack->active);
        result.producer_boot_id = CopyString(ack->producer_boot_id);
        if (result.operation != request.operation || result.target != request.target ||
            result.previous != request.previous) {
          dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
          continue;
        }
        dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
        return result;
      }
    }
    dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
    std::this_thread::sleep_for(std::chrono::milliseconds(20));
  }
  throw std::runtime_error("map_activation_timeout");
}

std::string JsonEscape(const std::string &value) {
  std::string output;
  for (const unsigned char character : value) {
    switch (character) {
      case '\\':
        output += "\\\\";
        break;
      case '"':
        output += "\\\"";
        break;
      case '\b':
        output += "\\b";
        break;
      case '\f':
        output += "\\f";
        break;
      case '\n':
        output += "\\n";
        break;
      case '\r':
        output += "\\r";
        break;
      case '\t':
        output += "\\t";
        break;
      default:
        if (character < 0x20U) {
          constexpr char kHex[] = "0123456789abcdef";
          output += "\\u00";
          output.push_back(kHex[character >> 4U]);
          output.push_back(kHex[character & 0x0fU]);
        } else {
          output.push_back(static_cast<char>(character));
        }
    }
  }
  return output;
}

void PrintIdentityJson(const MapIdentity &identity) {
  std::cout << "{\"present\":" << (identity.present ? "true" : "false") << ",\"map_id\":\""
            << JsonEscape(identity.map_id) << "\",\"version_id\":\""
            << JsonEscape(identity.version_id) << "\",\"frame_id\":\""
            << JsonEscape(identity.frame_id) << "\",\"map_dir\":\"" << JsonEscape(identity.map_dir)
            << "\",\"artifacts\":[";
  for (std::size_t index = 0U; index < identity.artifacts.size(); ++index) {
    if (index > 0U)
      std::cout << ',';
    const auto &artifact = identity.artifacts[index];
    std::cout << "{\"type\":\"" << JsonEscape(artifact.type) << "\",\"uri\":\""
              << JsonEscape(artifact.uri) << "\",\"sha256\":\"" << JsonEscape(artifact.sha256)
              << "\"}";
  }
  std::cout << "]}";
}

void PrintResult(const ActivationResult &result) {
  const std::string activation_token =
      result.operation == ActivationOperation::kStage && result.accepted
          ? EncodeActivationToken(result.target, result.previous)
          : std::string{};
  std::cout << "{\"schema_version\":\"lingtu.map_activation.v2\""
            << ",\"request_id\":\"" << JsonEscape(result.request_id) << "\",\"operation\":\""
            << ActivationOperationName(result.operation)
            << "\",\"accepted\":" << (result.accepted ? "true" : "false") << ",\"message\":\""
            << JsonEscape(result.message)
            << "\",\"changed\":" << (result.changed ? "true" : "false")
            << ",\"producer_boot_id\":\"" << JsonEscape(result.producer_boot_id)
            << "\",\"activation_token\":\"" << JsonEscape(activation_token) << "\",\"target\":";
  PrintIdentityJson(result.target);
  std::cout << ",\"previous\":";
  PrintIdentityJson(result.previous);
  std::cout << ",\"active\":";
  PrintIdentityJson(result.active);
  std::cout << "}\n";
}

void PrintError(const std::string &request_id, ActivationOperation operation,
                const std::string &message) {
  ActivationResult result;
  result.request_id = request_id;
  result.operation = operation;
  result.message = message;
  PrintResult(result);
}

}  // namespace

int main(int argc, char **argv) {
  ActivationOperation operation = ActivationOperation::kVerify;
  std::string request_id;
  try {
    const Options options = ParseOptions(argc, argv);
    operation = options.operation;
    request_id = options.request_id;
    MapStore store(MapStoreConfig{options.map_root});
    ActivationCoordinator identities(store);
    ActivationRequest request;
    request.request_id = options.request_id;
    request.operation = options.operation;
    request.caller = options.caller;
    request.reason = "product switch map activation";
    if (options.operation == ActivationOperation::kStage) {
      request.target = identities.IdentityFor(options.operand);
      request.previous = identities.ActiveIdentity();
    } else {
      auto decoded = DecodeActivationToken(options.operand);
      request.target = std::move(decoded.first);
      request.previous = std::move(decoded.second);
    }
    const ActivationResult result = CallMapd(options.domain_id, request, options.timeout);
    PrintResult(result);
    return result.accepted ? 0 : 2;
  } catch (const std::exception &exception) {
    PrintError(request_id, operation, exception.what());
    return 3;
  }
}
