#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <limits>
#include <optional>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "dds/dds.h"
#include "lingtu/maps/build/pipeline.hpp"
#include "lingtu/maps/mapd/activation.hpp"
#include "lingtu/maps/store.hpp"
#include "messages.h"
#include "message/cpp/qos.hpp"
#include "message/cpp/topics.hpp"

#if defined(_WIN32)
#include <process.h>
#else
#include <unistd.h>
#endif

namespace {

using lingtu::maps::MapStore;
using lingtu::maps::MapStoreConfig;
using lingtu::maps::MapPipelineCore;
using lingtu::maps::OctomapBuildOptions;
using lingtu::maps::mapd::ActivationCoordinator;
using lingtu::maps::mapd::DecodeActivationToken;
using lingtu::maps::mapd::EncodeActivationToken;
using lingtu::maps::mapd::ActivationOperation;
using lingtu::maps::mapd::ActivationRequest;
using lingtu::maps::mapd::ActivationResult;
using lingtu::maps::mapd::ArtifactIdentity;
using lingtu::maps::mapd::MapIdentity;

struct Options {
  ActivationOperation operation{ActivationOperation::kVerify};
  bool prepare_only{false};
  std::string operand;
  int domain_id{0};
  std::filesystem::path map_root;
  std::chrono::milliseconds timeout{5000};
  std::string caller{"product-control"};
  std::string request_id;
};

struct BuildOptions {
  std::string map_id;
  std::filesystem::path map_root;
  OctomapBuildOptions build;
};

std::string EnvOr(const char *name, std::string fallback) {
  const char *value = std::getenv(name);
  return value == nullptr || value[0] == '\0' ? std::move(fallback) : std::string{value};
}

std::filesystem::path ResolveMapRoot() {
  const char *configured = std::getenv("NAV_MAP_DIR");
  if (configured != nullptr && configured[0] != '\0') {
    return std::filesystem::absolute(configured).lexically_normal();
  }
  const char *home = std::getenv("HOME");
  if (home == nullptr || home[0] == '\0') {
    home = std::getenv("USERPROFILE");
  }
  if (home == nullptr || home[0] == '\0') {
    return std::filesystem::absolute("maps").lexically_normal();
  }
  return (std::filesystem::path(home) / "data" / "lingtu" / "maps").lexically_normal();
}

std::string MakeRequestId() {
#if defined(_WIN32)
  const int process_id = _getpid();
#else
  const int process_id = getpid();
#endif
  const auto stamp = std::chrono::steady_clock::now().time_since_epoch().count();
  return "mapctl-" + std::to_string(process_id) + "-" + std::to_string(stamp);
}

int ParseInt(const std::string &value, const char *field) {
  std::size_t consumed = 0U;
  const long parsed = std::stol(value, &consumed);
  if (consumed != value.size() || parsed < std::numeric_limits<int>::min() ||
      parsed > std::numeric_limits<int>::max()) {
    throw std::invalid_argument(std::string(field) + " is invalid");
  }
  return static_cast<int>(parsed);
}

double ParseDouble(const std::string &value, const char *field) {
  std::size_t consumed = 0U;
  const double parsed = std::stod(value, &consumed);
  if (consumed != value.size() || !std::isfinite(parsed)) {
    throw std::invalid_argument(std::string(field) + " is invalid");
  }
  return parsed;
}

void PrintUsage() {
  std::cout << "lingtu-mapctl build MAP_ID [options]\n"
            << "lingtu-mapctl prepare MAP_ID [options]\n"
            << "lingtu-mapctl stage MAP_ID [options]\n"
            << "lingtu-mapctl verify ACTIVATION_TOKEN [options]\n"
            << "lingtu-mapctl restore ACTIVATION_TOKEN [options]\n"
            << "  --domain-id N       CycloneDDS domain id\n"
            << "  --map-root PATH     saved-map root used to read exact identities\n"
            << "  --timeout-ms N      matching ACK deadline (default 5000)\n"
            << "  --request-id ID     idempotency key (generated by default)\n"
            << "  --caller NAME       audit caller (default product-control)\n";
}

BuildOptions ParseBuildOptions(int argc, char **argv) {
  if (argc < 3) {
    throw std::invalid_argument("build requires a map id");
  }
  BuildOptions options;
  options.map_id = argv[2];
  options.map_root = ResolveMapRoot();
  options.build.build_mode = "native_octomap";
  options.build.source_profile = "mapctl";
  options.build.data_source = "mapctl";
  for (int index = 3; index < argc; ++index) {
    const std::string argument = argv[index];
    const auto next = [&]() -> std::string {
      if (++index >= argc) {
        throw std::invalid_argument(argument + " requires a value");
      }
      return argv[index];
    };
    if (argument == "--map-root") {
      options.map_root = std::filesystem::absolute(next()).lexically_normal();
    } else if (argument == "--build-mode") {
      options.build.build_mode = next();
    } else if (argument == "--converter") {
      options.build.converter_command = next();
    } else if (argument == "--resolution") {
      options.build.resolution = ParseDouble(next(), "--resolution");
    } else if (argument == "--support-dilation-cells") {
      options.build.support_dilation_cells = ParseInt(next(), argument.c_str());
    } else if (argument == "--free-layers-above") {
      options.build.free_layers_above = ParseInt(next(), argument.c_str());
    } else if (argument == "--free-dilation-cells") {
      options.build.free_dilation_cells = ParseInt(next(), argument.c_str());
    } else if (argument == "--frame") {
      options.build.frame_id = next();
    } else if (argument == "--source-profile") {
      options.build.source_profile = next();
    } else if (argument == "--data-source") {
      options.build.data_source = next();
    } else if (argument == "--slam-source") {
      options.build.slam_source = next();
    } else if (argument == "--localization-source") {
      options.build.localization_source = next();
    } else if (argument == "--mapping-source") {
      options.build.mapping_source = next();
    } else if (argument == "--timeout-s") {
      options.build.timeout_sec = ParseDouble(next(), "--timeout-s");
    } else if (argument == "--help" || argument == "-h") {
      PrintUsage();
      std::exit(0);
    } else {
      throw std::invalid_argument("unknown build option: " + argument);
    }
  }
  if (!MapStore::IsValidMapId(options.map_id)) {
    throw std::invalid_argument("invalid map id");
  }
  if (options.build.resolution <= 0.0 || options.build.timeout_sec <= 0.0 ||
      options.build.support_dilation_cells < 0 || options.build.free_layers_above < 0 ||
      options.build.free_dilation_cells < 0 || options.build.frame_id.empty()) {
    throw std::invalid_argument("build geometry and timeout values must be positive");
  }
  return options;
}

Options ParseOptions(int argc, char **argv) {
  if (argc >= 2 && (std::string{argv[1]} == "--help" || std::string{argv[1]} == "-h")) {
    PrintUsage();
    std::exit(0);
  }
  if (argc < 3) {
    throw std::invalid_argument("operation and operand are required");
  }
  Options options;
  const std::string operation = argv[1];
  if (operation == "prepare") {
    options.operation = ActivationOperation::kStage;
    options.prepare_only = true;
  } else if (operation == "stage") {
    options.operation = ActivationOperation::kStage;
  } else if (operation == "restore") {
    options.operation = ActivationOperation::kRestore;
  } else if (operation == "verify") {
    options.operation = ActivationOperation::kVerify;
  } else {
    throw std::invalid_argument("operation must be prepare, stage, restore, or verify");
  }
  options.operand = argv[2];
  options.domain_id = ParseInt(EnvOr("LINGTU_DDS_DOMAIN_ID", "0"), "LINGTU_DDS_DOMAIN_ID");
  options.map_root = ResolveMapRoot();
  options.request_id = MakeRequestId();
  for (int index = 3; index < argc; ++index) {
    const std::string argument = argv[index];
    const auto next = [&]() -> std::string {
      if (++index >= argc) {
        throw std::invalid_argument(argument + " requires a value");
      }
      return argv[index];
    };
    if (argument == "--domain-id") {
      options.domain_id = ParseInt(next(), "--domain-id");
    } else if (argument == "--map-root") {
      options.map_root = std::filesystem::absolute(next()).lexically_normal();
    } else if (argument == "--timeout-ms") {
      const int timeout = ParseInt(next(), "--timeout-ms");
      if (timeout <= 0) {
        throw std::invalid_argument("--timeout-ms must be positive");
      }
      options.timeout = std::chrono::milliseconds(timeout);
    } else if (argument == "--request-id") {
      options.request_id = next();
    } else if (argument == "--caller") {
      options.caller = next();
    } else if (argument == "--help" || argument == "-h") {
      PrintUsage();
      std::exit(0);
    } else {
      throw std::invalid_argument("unknown option: " + argument);
    }
  }
  if (options.request_id.empty() || options.caller.empty()) {
    throw std::invalid_argument("request-id and caller must not be empty");
  }
  return options;
}

const char *CliOperationName(ActivationOperation operation) noexcept {
  switch (operation) {
    case ActivationOperation::kStage:
      return "stage";
    case ActivationOperation::kRestore:
      return "restore";
    case ActivationOperation::kVerify:
      return "verify";
  }
  return "unknown";
}

lingtu_dds_MapActivationOperation EncodeOperation(ActivationOperation operation) {
  switch (operation) {
    case ActivationOperation::kStage:
      return lingtu_dds_MAP_ACTIVATION_STAGE;
    case ActivationOperation::kRestore:
      return lingtu_dds_MAP_ACTIVATION_RESTORE;
    case ActivationOperation::kVerify:
      return lingtu_dds_MAP_ACTIVATION_VERIFY;
  }
  return lingtu_dds_MAP_ACTIVATION_VERIFY;
}

ActivationOperation DecodeOperation(lingtu_dds_MapActivationOperation value) {
  switch (value) {
    case lingtu_dds_MAP_ACTIVATION_STAGE:
      return ActivationOperation::kStage;
    case lingtu_dds_MAP_ACTIVATION_RESTORE:
      return ActivationOperation::kRestore;
    case lingtu_dds_MAP_ACTIVATION_VERIFY:
      return ActivationOperation::kVerify;
  }
  throw std::runtime_error("mapd returned an invalid activation operation");
}

void FillIdentity(const MapIdentity &identity, lingtu_dds_MapIdentity *message,
                  std::vector<lingtu_dds_MapArtifactIdentity> *artifacts) {
  message->present = identity.present;
  message->map_id = const_cast<char *>(identity.map_id.c_str());
  message->content_epoch = identity.content_epoch;
  message->frame_id = const_cast<char *>(identity.frame_id.c_str());
  artifacts->resize(identity.artifacts.size());
  for (std::size_t index = 0U; index < identity.artifacts.size(); ++index) {
    auto &output = (*artifacts)[index];
    const auto &input = identity.artifacts[index];
    output.type = const_cast<char *>(input.type.c_str());
    output.uri = const_cast<char *>(input.uri.c_str());
  }
  message->artifacts._maximum = static_cast<std::uint32_t>(artifacts->size());
  message->artifacts._length = static_cast<std::uint32_t>(artifacts->size());
  message->artifacts._buffer = artifacts->data();
  message->artifacts._release = false;
}

std::string CopyString(const char *value) {
  return value == nullptr ? std::string{} : std::string{value};
}

MapIdentity DecodeIdentity(const lingtu_dds_MapIdentity &message) {
  if (message.artifacts._maximum < message.artifacts._length || message.artifacts._length > 32U ||
      (message.artifacts._length > 0U && message.artifacts._buffer == nullptr)) {
    throw std::runtime_error("mapd returned a malformed map identity");
  }
  MapIdentity identity;
  identity.present = message.present;
  identity.map_id = CopyString(message.map_id);
  identity.content_epoch = message.content_epoch;
  identity.frame_id = CopyString(message.frame_id);
  identity.artifacts.reserve(message.artifacts._length);
  for (std::uint32_t index = 0U; index < message.artifacts._length; ++index) {
    const auto &artifact = message.artifacts._buffer[index];
    identity.artifacts.push_back({CopyString(artifact.type), CopyString(artifact.uri)});
  }
  return identity;
}

dds_entity_t Checked(dds_return_t value, const char *action) {
  if (value < 0) {
    throw std::runtime_error(std::string(action) + ": " + dds_strretcode(-value));
  }
  return static_cast<dds_entity_t>(value);
}

ActivationResult CallMapd(int domain_id, const ActivationRequest &request,
                          std::chrono::milliseconds timeout) {
  const auto participant =
      Checked(dds_create_participant(domain_id, nullptr, nullptr), "dds_create_participant");
  struct ParticipantGuard {
    dds_entity_t value;
    ~ParticipantGuard() { dds_delete(value); }
  } guard{participant};
  const auto publisher =
      Checked(dds_create_publisher(participant, nullptr, nullptr), "dds_create_publisher");
  const auto subscriber =
      Checked(dds_create_subscriber(participant, nullptr, nullptr), "dds_create_subscriber");
  const auto request_topic = Checked(
      dds_create_topic(participant, &lingtu_dds_MapActivationRequest_desc,
                       lingtu::message::kMapsActivationRequest.dds_topic.data(), nullptr, nullptr),
      "dds_create_topic(request)");
  const auto ack_topic = Checked(
      dds_create_topic(participant, &lingtu_dds_MapActivationAck_desc,
                       lingtu::message::kMapsActivationAck.dds_topic.data(), nullptr, nullptr),
      "dds_create_topic(ack)");
  auto request_qos = lingtu::dds::make_qos(
      lingtu::dds::qos_for_topic(lingtu::message::kMapsActivationRequest.dds_topic));
  auto ack_qos = lingtu::dds::make_qos(
      lingtu::dds::qos_for_topic(lingtu::message::kMapsActivationAck.dds_topic));
  const auto writer =
      Checked(dds_create_writer(publisher, request_topic, request_qos.get(), nullptr),
              "dds_create_writer(request)");
  const auto reader = Checked(dds_create_reader(subscriber, ack_topic, ack_qos.get(), nullptr),
                              "dds_create_reader(ack)");

  lingtu_dds_MapActivationRequest message{};
  message.request_id = const_cast<char *>(request.request_id.c_str());
  message.operation = EncodeOperation(request.operation);
  std::vector<lingtu_dds_MapArtifactIdentity> target_artifacts;
  std::vector<lingtu_dds_MapArtifactIdentity> previous_artifacts;
  FillIdentity(request.target, &message.target, &target_artifacts);
  FillIdentity(request.previous, &message.previous, &previous_artifacts);
  message.caller = const_cast<char *>(request.caller.c_str());
  message.reason = const_cast<char *>(request.reason.c_str());

  const auto deadline = std::chrono::steady_clock::now() + timeout;
  auto next_write = std::chrono::steady_clock::now();
  while (std::chrono::steady_clock::now() < deadline) {
    const auto now = std::chrono::steady_clock::now();
    if (now >= next_write) {
      Checked(dds_write(writer, &message), "dds_write(request)");
      next_write = now + std::chrono::milliseconds(500);
    }
    void *sample = dds_alloc(sizeof(lingtu_dds_MapActivationAck));
    std::memset(sample, 0, sizeof(lingtu_dds_MapActivationAck));
    void *samples[1] = {sample};
    dds_sample_info_t info{};
    const dds_return_t count = dds_take(reader, samples, &info, 1U, 1U);
    if (count < 0) {
      dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
      Checked(count, "dds_take(ack)");
    }
    if (count == 1 && info.valid_data) {
      const auto *ack = static_cast<lingtu_dds_MapActivationAck *>(sample);
      if (CopyString(ack->request_id) == request.request_id) {
        ActivationResult result;
        result.request_id = request.request_id;
        result.operation = DecodeOperation(ack->operation);
        result.accepted = ack->accepted;
        result.message = CopyString(ack->message);
        result.changed = ack->changed;
        result.target = DecodeIdentity(ack->target);
        result.previous = DecodeIdentity(ack->previous);
        result.active = DecodeIdentity(ack->active);
        result.producer_boot_id = CopyString(ack->producer_boot_id);
        if (result.operation != request.operation || result.target != request.target ||
            result.previous != request.previous) {
          dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
          continue;
        }
        dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
        return result;
      }
    }
    dds_sample_free(sample, &lingtu_dds_MapActivationAck_desc, DDS_FREE_ALL);
    std::this_thread::sleep_for(std::chrono::milliseconds(20));
  }
  throw std::runtime_error("map_activation_timeout");
}

std::string JsonEscape(const std::string &value) {
  std::string output;
  for (const unsigned char character : value) {
    switch (character) {
      case '\\':
        output += "\\\\";
        break;
      case '"':
        output += "\\\"";
        break;
      case '\b':
        output += "\\b";
        break;
      case '\f':
        output += "\\f";
        break;
      case '\n':
        output += "\\n";
        break;
      case '\r':
        output += "\\r";
        break;
      case '\t':
        output += "\\t";
        break;
      default:
        if (character < 0x20U) {
          constexpr char kHex[] = "0123456789abcdef";
          output += "\\u00";
          output.push_back(kHex[character >> 4U]);
          output.push_back(kHex[character & 0x0fU]);
        } else {
          output.push_back(static_cast<char>(character));
        }
    }
  }
  return output;
}

int RunBuild(int argc, char **argv) {
  try {
    const BuildOptions options = ParseBuildOptions(argc, argv);
    MapStore store(MapStoreConfig{options.map_root});
    MapPipelineCore pipeline(store);
    const std::string result =
        pipeline.BuildOctomapArtifactJson(options.map_id, options.build);
    const bool build_success = result.find("\"success\":true") != std::string::npos;
    std::cout << result << '\n';
    return build_success ? 0 : 2;
  } catch (const std::exception &exception) {
    std::cout << "{\"action\":\"build_octomap\",\"success\":false,\"message\":\""
              << JsonEscape(exception.what()) << "\"}\n";
    return 3;
  }
}

void PrintIdentityJson(const MapIdentity &identity) {
  std::cout << "{\"present\":" << (identity.present ? "true" : "false") << ",\"map_id\":\""
            << JsonEscape(identity.map_id) << "\",\"content_epoch\":"
            << identity.content_epoch << ",\"frame_id\":\""
            << JsonEscape(identity.frame_id) << "\",\"artifacts\":[";
  for (std::size_t index = 0U; index < identity.artifacts.size(); ++index) {
    if (index > 0U)
      std::cout << ',';
    const auto &artifact = identity.artifacts[index];
    std::cout << "{\"type\":\"" << JsonEscape(artifact.type) << "\",\"uri\":\""
              << JsonEscape(artifact.uri) << "\"}";
  }
  std::cout << "]}";
}

void PrintResult(const ActivationResult &result, const std::string &operation_name = {}) {
  const std::string activation_token =
      result.operation == ActivationOperation::kStage && result.accepted
          ? EncodeActivationToken(result.target, result.previous)
          : std::string{};
  std::cout << "{\"schema_version\":\"lingtu.map_activation.v2\""
            << ",\"request_id\":\"" << JsonEscape(result.request_id) << "\",\"operation\":\""
            << (operation_name.empty() ? CliOperationName(result.operation)
                                       : operation_name)
            << "\",\"accepted\":" << (result.accepted ? "true" : "false") << ",\"message\":\""
            << JsonEscape(result.message)
            << "\",\"changed\":" << (result.changed ? "true" : "false")
            << ",\"producer_boot_id\":\"" << JsonEscape(result.producer_boot_id)
            << "\",\"activation_token\":\"" << JsonEscape(activation_token) << "\",\"target\":";
  PrintIdentityJson(result.target);
  std::cout << ",\"previous\":";
  PrintIdentityJson(result.previous);
  std::cout << ",\"active\":";
  PrintIdentityJson(result.active);
  std::cout << "}\n";
}

void PrintError(const std::string &request_id, ActivationOperation operation,
                const std::string &operation_name,
                const std::string &message) {
  ActivationResult result;
  result.request_id = request_id;
  result.operation = operation;
  result.message = message;
  PrintResult(result, operation_name);
}

}  // namespace

int main(int argc, char **argv) {
  if (argc >= 2 && std::string{argv[1]} == "build") {
    return RunBuild(argc, argv);
  }
  ActivationOperation operation = ActivationOperation::kVerify;
  std::string operation_name;
  std::string request_id;
  try {
    const Options options = ParseOptions(argc, argv);
    operation = options.operation;
    operation_name = options.prepare_only ? "prepare" : CliOperationName(operation);
    request_id = options.request_id;
    MapStore store(MapStoreConfig{options.map_root});
    ActivationCoordinator identities(store);
    ActivationRequest request;
    if (options.operation == ActivationOperation::kStage) {
      request = identities.PrepareStage(options.operand);
    } else {
      auto decoded = DecodeActivationToken(options.operand);
      request.target = std::move(decoded.first);
      request.previous = std::move(decoded.second);
    }
    request.request_id = options.request_id;
    request.operation = options.operation;
    request.caller = options.caller;
    request.reason = "product switch map activation";
    if (options.prepare_only) {
      const ActivationResult prepared{
          request.request_id, request.operation, true, "prepared", false,
          request.target, request.previous, request.previous, {}};
      PrintResult(prepared, operation_name);
      return 0;
    }
    if (options.operation == ActivationOperation::kStage) {
      const MapIdentity actual_target = identities.IdentityFor(request.target.map_id);
      const MapIdentity actual_previous = identities.ActiveIdentity();
      if (actual_target != request.target) {
        throw std::runtime_error("target_identity_mismatch");
      }
      if (actual_previous != request.previous) {
        throw std::runtime_error("previous_identity_mismatch");
      }
    }
    const ActivationResult result = CallMapd(options.domain_id, request, options.timeout);
    PrintResult(result);
    return result.accepted ? 0 : 2;
  } catch (const std::exception &exception) {
    PrintError(request_id, operation, operation_name, exception.what());
    return 3;
  }
}
