module lingtu {
module dds {

struct Time {
  long sec;
  unsigned long nanosec;
};

struct Header {
  Time stamp;
  string frame_id;
};

struct Vector3 {
  double x;
  double y;
  double z;
};

struct Quaternion {
  double x;
  double y;
  double z;
  double w;
};

struct Imu {
  Header header;
  Quaternion orientation;
  double orientation_covariance[9];
  Vector3 angular_velocity;
  double angular_velocity_covariance[9];
  Vector3 linear_acceleration;
  double linear_acceleration_covariance[9];
};

struct LivoxPoint {
  unsigned long offset_time;
  float x;
  float y;
  float z;
  octet reflectivity;
  octet tag;
  octet line;
};

struct LivoxFrame {
  Header header;
  unsigned long long timebase;
  unsigned long point_num;
  octet lidar_id;
  octet rsvd[3];
  sequence<LivoxPoint> points;
};

struct Point {
  double x;
  double y;
  double z;
};

struct Pose {
  Point position;
  Quaternion orientation;
};

struct PoseStamped {
  Header header;
  Pose pose;
};

struct PoseWithCovariance {
  Pose pose;
  double covariance[36];
};

struct Twist {
  Vector3 linear;
  Vector3 angular;
};

struct TwistStamped {
  Header header;
  Twist twist;
};

struct FinalVelocityCommand {
  string host_boot_id;
  string producer_boot_id;
  unsigned long long output_seq;
  unsigned long long source_boottime_ns;
  unsigned long long source_wall_ns;
  Twist twist;
};

struct Transform {
  Vector3 translation;
  Quaternion rotation;
};

struct TransformStamped {
  Header header;
  string child_frame_id;
  Transform transform;
};

struct TFMessage {
  sequence<TransformStamped> transforms;
};

struct TwistWithCovariance {
  Twist twist;
  double covariance[36];
};

struct Odometry {
  Header header;
  string child_frame_id;
  PoseWithCovariance pose;
  TwistWithCovariance twist;
};

struct PointField {
  string name;
  unsigned long offset;
  octet datatype;
  unsigned long count;
};

struct PointCloud2 {
  Header header;
  unsigned long height;
  unsigned long width;
  sequence<PointField> fields;
  boolean is_bigendian;
  unsigned long point_step;
  unsigned long row_step;
  sequence<octet> data;
  boolean is_dense;
};

struct Image {
  Header header;
  unsigned long height;
  unsigned long width;
  string encoding;
  boolean is_bigendian;
  unsigned long step;
  sequence<octet> data;
};

struct CameraInfo {
  Header header;
  unsigned long height;
  unsigned long width;
  double depth_scale;
  string distortion_model;
  sequence<double> d;
  double k[9];
  double r[9];
  double p[12];
};

struct GnssFix {
  Header header;
  double latitude;
  double longitude;
  double altitude;
  long fix_type;
  double position_covariance[9];
  unsigned long num_sat;
  unsigned long num_sat_used;
  double hdop;
  double rtcm_age_s;
};

struct GnssStatus {
  Header header;
  string device;
  long fix_type;
  boolean link_ok;
  boolean rtk;
  unsigned long num_sat;
  unsigned long num_sat_used;
  double hdop;
  double rtcm_age_s;
  string error;
};

struct DriverControlState {
  Header header;
  boolean connected;
  boolean ready;
  boolean motors_enabled;
  boolean critical_fault;
  boolean lease_valid;
  unsigned long lease_remaining_ms;
  unsigned long long accepted_sequence;
  boolean last_command_accepted;
  string fsm;
  string owner;
  string owner_id;
  string reason;
};

struct Float32 {
  float data;
};

struct Bool {
  boolean data;
};

struct Text {
  string data;
};

struct NavigationCommandRequest {
  Header header;
  string request_id;
  long kind;
  Pose goal;
  Twist velocity;
  string reason;
};

struct NavigationCommandAck {
  Header header;
  string request_id;
  long kind;
  boolean accepted;
  string reason;
};

struct InspectionCommandRequest {
  Header header;
  string request_id;
  long kind;
  string route_id;
  unsigned long long route_revision;
  string reason;
};

struct InspectionCommandAck {
  Header header;
  string request_id;
  long kind;
  boolean accepted;
  string reason;
  string run_id;
};

struct InspectionEvidenceRequest {
  Header header;
  string request_id;
  string run_id;
  string route_id;
  unsigned long long revision;
  string map_id;
  long long map_version;
  unsigned long point_index;
  string point_id;
  string action;
  double deadline_s;
};

struct InspectionEvidenceResult {
  Header header;
  string request_id;
  string evidence_id;
  boolean persisted;
  string reason;
  string analysis_verdict;
};

struct InspectionStatus {
  Header header;
  string run_id;
  string route_id;
  unsigned long long route_revision;
  long state;
  unsigned long point_index;
  unsigned long point_count;
  unsigned long loop_index;
  unsigned long retry_count;
  string point_id;
  string action;
  string action_request_id;
  string evidence_id;
  double phase_started_at;
  double stable_since;
  double deadline;
  string reason;
};

struct RelocalizationRequest {
  string request_id;
  string action;
  string engine;
  string map_path;
  boolean has_initial_pose;
  Pose initial_pose;
  double timeout_s;
};

struct RelocalizationResponse {
  string request_id;
  string action;
  string engine;
  boolean success;
  string message;
  double quality;
  boolean map_loaded;
  boolean has_map_body;
  Pose map_body;
  boolean has_map_odom;
  Pose map_odom;
  string state;
  string refine_backend;
  long refine_iterations;
  long refine_inliers;
  boolean refine_converged;
  double refine_pos_cov_trace;
  boolean track_against_map_supported;
  boolean track_against_map_enabled;
  long track_against_map_failures;
};

struct Path {
  Header header;
  sequence<PoseStamped> poses;
};

struct MapMetaData {
  Time map_load_time;
  float resolution;
  unsigned long width;
  unsigned long height;
  Pose origin;
};

struct OccupancyGrid {
  Header header;
  MapMetaData info;
  sequence<octet> data;
};

};
};
