#!/usr/bin/env bash
# Thunder lightweight runtime environment.
#
# This file is intentionally free of ROS setup. It is the shared deployment
# environment for native endpoints and the optional Python application graph.

: "${LINGTU_REPO:=/opt/lingtu/current}"
: "${LINGTU_ENV:=real}"
: "${LINGTU_DATA_SOURCE:=thunder}"
: "${LINGTU_RUNTIME_CONTRACT:=real}"
: "${LINGTU_MODULE_TRANSPORT:=local}"
: "${LINGTU_ENDPOINT_TRANSPORT:=local}"
: "${LINGTU_ENDPOINT_CONTRACT:=}"
: "${LINGTU_SIMULATION_ONLY:=0}"
: "${LINGTU_ENABLE_ROBOT_DRIVER:=1}"
: "${LINGTU_COMMAND_OUTPUT_MODE:=local_driver}"
: "${LINGTU_HARDWARE_CONTROL_BOUNDARY:=module_graph_driver}"
: "${LINGTU_GATEWAY_PORT:=5050}"
: "${LINGTU_MAP_ARTIFACT_CONVERTER:=${LINGTU_REPO}/build/octoplanner3d_headless/octoplanner3d_pcd_to_octomap}"
: "${LINGTU_MAPS_LIB:=${LINGTU_REPO}/build/maps/liblingtu_maps.so}"
: "${NAV_MAP_DIR:=/home/sunrise/data/nova/maps}"
: "${LINGTU_NAV_GLOBAL_PLANNER:=octoplanner3d}"
: "${LINGTU_ACTIVE_OCTOMAP:=${NAV_MAP_DIR}/active/octomap.ot}"
: "${LINGTU_ACTIVE_OCCUPANCY:=${NAV_MAP_DIR}/active/occupancy.npz}"
if [ -z "${LINGTU_ACTIVE_PLANNER_MAP:-}" ]; then
    case "${LINGTU_NAV_GLOBAL_PLANNER}" in
        octoplanner3d|octo)
            LINGTU_ACTIVE_PLANNER_MAP="${LINGTU_ACTIVE_OCTOMAP}"
            ;;
        far)
            LINGTU_ACTIVE_PLANNER_MAP="${LINGTU_ACTIVE_OCCUPANCY}"
            ;;
        *)
            echo "ERROR: unsupported LINGTU_NAV_GLOBAL_PLANNER=${LINGTU_NAV_GLOBAL_PLANNER}" >&2
            return 2 2>/dev/null || exit 2
            ;;
    esac
fi
# Keep the native field planner aligned with THUNDER_OCTO_CONFIG.
# Existing environment or systemd drop-in values remain authoritative.
: "${LINGTU_NAV_OCTO_ROBOT_RADIUS_M:=0.25}"
: "${LINGTU_NAV_OCTO_MAX_ITERATIONS:=500000}"
: "${LINGTU_NAV_OCTO_SNAP_RADIUS_CELLS:=24}"
: "${LINGTU_NAV_OCTO_REQUIRE_GROUND_SUPPORT:=1}"
: "${LINGTU_NAV_OCTO_STRICT_GROUND_SUPPORT:=0}"
: "${LINGTU_NAV_OCTO_GROUND_SUPPORT_XY_RADIUS_CELLS:=2}"
: "${LINGTU_NAV_OCTO_GROUND_SUPPORT_DEPTH_CELLS:=2}"
: "${LINGTU_NAV_OCTO_ENABLE_PREBLOCKED_COSTMAP:=1}"
: "${LINGTU_NAV_OCTO_PREBLOCKED_RADIUS_CELLS:=3}"
: "${LINGTU_NAV_OCTO_PREBLOCKED_WEIGHT:=2.5}"
: "${LINGTU_NAV_OCTO_LOWEST_TRAVERSABLE_ONLY:=0}"
: "${LINGTU_NAV_OCTO_FLOOR_CHANGE_PENALTY:=6.0}"
: "${LINGTU_NAV_OCTO_MAX_STEP_HEIGHT_M:=0.45}"
: "${LINGTU_NAV_OCTO_MAX_SLOPE:=0.0}"
: "${LINGTU_NAV_OCTO_SAME_FLOOR_PREFERENCE:=1}"
: "${LINGTU_NAV_OCTO_SAME_FLOOR_Z_TOLERANCE_M:=0.75}"
: "${LINGTU_NAV_OCTO_MAX_SAME_FLOOR_Z_EXCURSION_M:=2.0}"
: "${LINGTU_NAV_OCTO_OBSTACLE_CLEARANCE_RADIUS_CELLS:=2}"
: "${LINGTU_NAV_OCTO_OBSTACLE_CLEARANCE_WEIGHT:=1.5}"
# FAR is an optional 2D visibility-graph backend. Unknown-space fallback is
# disabled by default; field enablement must be an explicit product decision.
: "${LINGTU_NAV_FAR_ROBOT_RADIUS_M:=0.35}"
: "${LINGTU_NAV_FAR_OBSTACLE_CLEARANCE_M:=0.10}"
: "${LINGTU_NAV_FAR_MAX_VISIBILITY_DISTANCE_M:=30.0}"
: "${LINGTU_NAV_FAR_UNKNOWN_COST_MULTIPLIER:=6.0}"
: "${LINGTU_NAV_FAR_CORNER_SEPARATION_CELLS:=1}"
: "${LINGTU_NAV_FAR_SNAP_RADIUS_CELLS:=12}"
: "${LINGTU_NAV_FAR_MAX_GRAPH_NODES:=4096}"
: "${LINGTU_NAV_FAR_MAX_VISIBILITY_PAIRS:=500000}"
: "${LINGTU_NAV_FAR_MAX_SEARCH_EXPANSIONS:=500000}"
: "${LINGTU_NAV_FAR_ALLOW_UNKNOWN_FALLBACK:=0}"
: "${LINGTU_NAV_FAR_SIMPLIFY_PATH:=1}"
# Native TARE is driven by identity-versioned rolling occupancy snapshots.
: "${LINGTU_EXPLORE_TICK_HZ:=2}"
: "${LINGTU_EXPLORE_ROUTE:=map}"
: "${LINGTU_EXPLORE_COMMAND_RETRY_S:=3}"
: "${LINGTU_EXPLORE_COMMAND_TIMEOUT_MS:=10000}"
: "${LINGTU_EXPLORE_ARRIVAL_TOLERANCE_M:=0.65}"
: "${LINGTU_EXPLORE_GOAL_TIMEOUT_S:=180}"
: "${LINGTU_EXPLORE_STATUS_PERIOD_S:=2}"
: "${LINGTU_EXPLORE_STATUS_MAX_AGE_S:=6.0}"
: "${LINGTU_EXPLORE_CONTROL_MAX_AGE_S:=2.0}"
: "${LINGTU_EXPLORE_ODOM_MAX_AGE_S:=0.50}"
: "${LINGTU_EXPLORE_SNAPSHOT_MAX_AGE_S:=2.0}"
: "${LINGTU_EXPLORE_TF_MAX_AGE_S:=1.0}"
: "${LINGTU_EXPLORE_FUTURE_TOLERANCE_S:=0.50}"
: "${LINGTU_EXPLORE_MIN_FRONTIER_SIZE:=3}"
: "${LINGTU_EXPLORE_SENSOR_RANGE_M:=5.0}"
: "${LINGTU_EXPLORE_CANDIDATE_RADIUS_M:=2.5}"
: "${LINGTU_EXPLORE_MIN_GOAL_DISTANCE_M:=0.8}"
: "${LINGTU_EXPLORE_NOVELTY_RADIUS_M:=1.0}"
: "${LINGTU_EXPLORE_MAX_CANDIDATES:=16}"
: "${LINGTU_EXPLORE_COVERAGE_RESOLUTION_M:=0.5}"
: "${LINGTU_EXPLORE_LOCAL_ROUTE_RADIUS_M:=12.0}"
: "${LINGTU_EXPLORE_RETURN_HOME_DISTANCE_M:=0.75}"
: "${LINGTU_EXPLORE_KEYPOSE_MIN_DISTANCE_M:=0.75}"
: "${LINGTU_EXPLORE_KEYPOSE_CONNECT_DISTANCE_M:=6.0}"
: "${LINGTU_EXPLORE_GAIN_WEIGHT:=1.0}"
: "${LINGTU_EXPLORE_TRAVEL_WEIGHT:=0.20}"
: "${LINGTU_EXPLORE_MOMENTUM_WEIGHT:=2.0}"
: "${LINGTU_EXPLORE_REVISIT_WEIGHT:=3.0}"
: "${LINGTU_EXPLORE_MAX_PLAN_TIME_MS:=100.0}"
: "${LINGTU_EXPLORE_ROUTE_2OPT_ITERATIONS:=4}"
: "${LINGTU_EXPLORE_MAX_GRID_CELLS:=1000000}"
: "${LINGTU_EXPLORE_MAX_FRONTIER_CELLS:=200000}"
: "${LINGTU_EXPLORE_MAX_FRONTIER_CLUSTERS:=512}"
: "${LINGTU_EXPLORE_MAX_COVERAGE_CELLS:=500000}"
: "${LINGTU_EXPLORE_MAX_KEYPOSES:=4096}"
: "${LINGTU_EXPLORE_MAX_KEYPOSE_EDGES:=16384}"
: "${LINGTU_EXPLORE_MAX_KEYPOSE_NEIGHBOR_LINKS:=6}"
: "${LINGTU_EXPLORE_MAX_ROUTE_TARGETS:=32}"
: "${LINGTU_EXPLORE_RETURN_HOME:=1}"
: "${LINGTU_LIVOX_CONFIG_DIR:=/opt/lingtu/config/livox}"
: "${LINGTU_LIVOX_NET_IFACE:=eth1}"
: "${LINGTU_LIVOX_HOST_IP:=}"
: "${LINGTU_LIVOX_LIDAR_IP:=}"
: "${LINGTU_LIVOX_BIND_LIDAR_IP:=0}"

if [ -d "${LINGTU_REPO}/src" ]; then
    export PYTHONPATH="${LINGTU_REPO}/src${PYTHONPATH:+:${PYTHONPATH}}"
fi

export LINGTU_REPO
export LINGTU_ENV
export LINGTU_DATA_SOURCE
export LINGTU_RUNTIME_CONTRACT
export LINGTU_PROFILE
export LINGTU_MODULE_TRANSPORT
export LINGTU_ENDPOINT_TRANSPORT
export LINGTU_ENDPOINT_CONTRACT
export LINGTU_SIMULATION_ONLY
export LINGTU_ENABLE_ROBOT_DRIVER
export LINGTU_COMMAND_OUTPUT_MODE
export LINGTU_HARDWARE_CONTROL_BOUNDARY
export LINGTU_GATEWAY_PORT
export LINGTU_MAP_ARTIFACT_CONVERTER
export LINGTU_MAPS_LIB
export NAV_MAP_DIR
export LINGTU_NAV_GLOBAL_PLANNER
export LINGTU_ACTIVE_PLANNER_MAP
export LINGTU_ACTIVE_OCTOMAP
export LINGTU_ACTIVE_OCCUPANCY
export LINGTU_NAV_OCTO_ROBOT_RADIUS_M
export LINGTU_NAV_OCTO_MAX_ITERATIONS
export LINGTU_NAV_OCTO_SNAP_RADIUS_CELLS
export LINGTU_NAV_OCTO_REQUIRE_GROUND_SUPPORT
export LINGTU_NAV_OCTO_STRICT_GROUND_SUPPORT
export LINGTU_NAV_OCTO_GROUND_SUPPORT_XY_RADIUS_CELLS
export LINGTU_NAV_OCTO_GROUND_SUPPORT_DEPTH_CELLS
export LINGTU_NAV_OCTO_ENABLE_PREBLOCKED_COSTMAP
export LINGTU_NAV_OCTO_PREBLOCKED_RADIUS_CELLS
export LINGTU_NAV_OCTO_PREBLOCKED_WEIGHT
export LINGTU_NAV_OCTO_LOWEST_TRAVERSABLE_ONLY
export LINGTU_NAV_OCTO_FLOOR_CHANGE_PENALTY
export LINGTU_NAV_OCTO_MAX_STEP_HEIGHT_M
export LINGTU_NAV_OCTO_MAX_SLOPE
export LINGTU_NAV_OCTO_SAME_FLOOR_PREFERENCE
export LINGTU_NAV_OCTO_SAME_FLOOR_Z_TOLERANCE_M
export LINGTU_NAV_OCTO_MAX_SAME_FLOOR_Z_EXCURSION_M
export LINGTU_NAV_OCTO_OBSTACLE_CLEARANCE_RADIUS_CELLS
export LINGTU_NAV_OCTO_OBSTACLE_CLEARANCE_WEIGHT
export LINGTU_NAV_FAR_ROBOT_RADIUS_M
export LINGTU_NAV_FAR_OBSTACLE_CLEARANCE_M
export LINGTU_NAV_FAR_MAX_VISIBILITY_DISTANCE_M
export LINGTU_NAV_FAR_UNKNOWN_COST_MULTIPLIER
export LINGTU_NAV_FAR_CORNER_SEPARATION_CELLS
export LINGTU_NAV_FAR_SNAP_RADIUS_CELLS
export LINGTU_NAV_FAR_MAX_GRAPH_NODES
export LINGTU_NAV_FAR_MAX_VISIBILITY_PAIRS
export LINGTU_NAV_FAR_MAX_SEARCH_EXPANSIONS
export LINGTU_NAV_FAR_ALLOW_UNKNOWN_FALLBACK
export LINGTU_NAV_FAR_SIMPLIFY_PATH
export LINGTU_EXPLORE_TICK_HZ
export LINGTU_EXPLORE_ROUTE
export LINGTU_EXPLORE_COMMAND_RETRY_S
export LINGTU_EXPLORE_COMMAND_TIMEOUT_MS
export LINGTU_EXPLORE_ARRIVAL_TOLERANCE_M
export LINGTU_EXPLORE_GOAL_TIMEOUT_S
export LINGTU_EXPLORE_STATUS_PERIOD_S
export LINGTU_EXPLORE_STATUS_MAX_AGE_S
export LINGTU_EXPLORE_CONTROL_MAX_AGE_S
export LINGTU_EXPLORE_ODOM_MAX_AGE_S
export LINGTU_EXPLORE_SNAPSHOT_MAX_AGE_S
export LINGTU_EXPLORE_TF_MAX_AGE_S
export LINGTU_EXPLORE_FUTURE_TOLERANCE_S
export LINGTU_EXPLORE_MIN_FRONTIER_SIZE
export LINGTU_EXPLORE_SENSOR_RANGE_M
export LINGTU_EXPLORE_CANDIDATE_RADIUS_M
export LINGTU_EXPLORE_MIN_GOAL_DISTANCE_M
export LINGTU_EXPLORE_NOVELTY_RADIUS_M
export LINGTU_EXPLORE_MAX_CANDIDATES
export LINGTU_EXPLORE_COVERAGE_RESOLUTION_M
export LINGTU_EXPLORE_LOCAL_ROUTE_RADIUS_M
export LINGTU_EXPLORE_RETURN_HOME_DISTANCE_M
export LINGTU_EXPLORE_KEYPOSE_MIN_DISTANCE_M
export LINGTU_EXPLORE_KEYPOSE_CONNECT_DISTANCE_M
export LINGTU_EXPLORE_GAIN_WEIGHT
export LINGTU_EXPLORE_TRAVEL_WEIGHT
export LINGTU_EXPLORE_MOMENTUM_WEIGHT
export LINGTU_EXPLORE_REVISIT_WEIGHT
export LINGTU_EXPLORE_MAX_PLAN_TIME_MS
export LINGTU_EXPLORE_ROUTE_2OPT_ITERATIONS
export LINGTU_EXPLORE_MAX_GRID_CELLS
export LINGTU_EXPLORE_MAX_FRONTIER_CELLS
export LINGTU_EXPLORE_MAX_FRONTIER_CLUSTERS
export LINGTU_EXPLORE_MAX_COVERAGE_CELLS
export LINGTU_EXPLORE_MAX_KEYPOSES
export LINGTU_EXPLORE_MAX_KEYPOSE_EDGES
export LINGTU_EXPLORE_MAX_KEYPOSE_NEIGHBOR_LINKS
export LINGTU_EXPLORE_MAX_ROUTE_TARGETS
export LINGTU_EXPLORE_RETURN_HOME
export LINGTU_LIVOX_CONFIG_DIR
export LINGTU_LIVOX_NET_IFACE
export LINGTU_LIVOX_HOST_IP
export LINGTU_LIVOX_LIDAR_IP
export LINGTU_LIVOX_BIND_LIDAR_IP
