rmf_fleet:
  name: "lingtu"
  limits:
    linear: [0.4, 1.0]
    angular: [0.785, 1.5]
  profile:
    footprint: 0.55
    vicinity: 0.75
  reversible: true
  battery_system:
    voltage: 48.0
    capacity: 20.0
    charging_current: 5.0
  mechanical_system:
    mass: 40.0
    moment_of_inertia: 20.0
    friction_coefficient: 0.22
  ambient_system:
    power: 50.0
  tool_system:
    power: 0.0
  recharge_threshold: 0.10
  recharge_soc: 1.0
  publish_fleet_state: 2.0
  account_for_battery_drain: false
  task_capabilities:
    loop: true
    delivery: false
  actions: []
  finishing_request: "nothing"
  responsive_wait: false
  robots:
    thunder-01:
      charger: "thunder-01_charger"
