"""Generate topic bindings, wire enums, and diagnostic fields from message sources."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from message.catalog import load_topics

PYTHON_OUTPUT = ROOT / "src" / "message" / "topics.py"
CPP_OUTPUT = ROOT / "src" / "message" / "generated" / "topics.hpp"
IDL_DIR = ROOT / "src" / "message" / "idl"
IDL_OUTPUT = IDL_DIR / "messages.idl"
IDL_DOMAINS = (
    "constants",
    "common",
    "sensors",
    "localization",
    "maps",
    "navigation",
    "exploration",
    "inspection",
)


def load_constants() -> dict[str, dict[str, int]]:
    source = (IDL_DIR / "constants.idl").read_text(encoding="utf-8")
    return {
        name: {key: int(value) for key, value in re.findall(r"const long (\w+) = (-?\d+);", body)}
        for name, body in re.findall(r"module (\w+) \{([^{}]*)\};", source)
    }


def render_python_enums(constants: dict[str, dict[str, int]]) -> str:
    blocks = ["# Generated from message/idl/constants.idl. Do not edit.\nfrom enum import IntEnum"]
    for name, members in constants.items():
        blocks.append(f"class {name}(IntEnum):\n" + "\n".join(f"    {key} = {value}" for key, value in members.items()))
    return "\n\n\n".join(blocks) + "\n"


def render_cpp_enums(constants: dict[str, dict[str, int]]) -> str:
    # Preserve existing C++ spelling while IDL owns every numeric value.
    names = {"NavigationControlMode": "NavigationControlState", "NavigationLifecycle": "NavigationLifecycleState"}
    plain = {"NavigationCommandKind", "NavigationGoalState", "OperatorMotionAction"}
    members = {
        ("NavigationCommandKind", "PAUSE_TASK"): "TaskPause",
        ("NavigationCommandKind", "RESUME_TASK"): "TaskResume",
    }
    lines = [
        "// Generated from message/idl/constants.idl. Do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "namespace lingtu::message {",
    ]
    for name, values in constants.items():
        lines.append(f"enum class {names.get(name, name)} : std::int32_t {{")
        for key, value in values.items():
            member = members.get((name, key), "".join(part.title() for part in key.split("_")))
            lines.append(f"  {'' if name in plain else 'k'}{member} = {value},")
        lines.append("};")
    return "\n".join([*lines, "}  // namespace lingtu::message", ""])


def render_schema() -> str:
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", render_idl(), flags=re.S)
    fields = {}
    for name, body in re.findall(r"struct (\w+)\s*\{([^{}]*)\};", source):
        members = []
        for declaration in body.split(";"):
            if not declaration.strip():
                continue
            match = re.search(r"\b(\w+)\s*(?:\[[^]]+\])?\s*$", declaration)
            if match is None:
                raise ValueError(f"unsupported IDL field in {name}: {declaration}")
            members.append(match.group(1))
        fields[f"lingtu.dds.{name}"] = tuple(members)
    return (
        "# Generated from message/idl/*.idl. Do not edit.\nMESSAGE_FIELDS = {\n"
        + "".join(f"    {name!r}: {members!r},\n" for name, members in sorted(fields.items()))
        + "}\n"
    )


def render_python(topics: list[dict[str, Any]]) -> str:
    fields = "\n".join(f'    {spec["name"]}: str = "{spec["topic"]}"' for spec in topics)
    dds_specs = "\n".join(
        f"    {json.dumps(spec['topic'])}: TopicSpec(\n"
        + "\n".join(
            f"        {json.dumps(str(spec[field]))},"
            for field in ("topic", "dds_topic", "message_type", "qos_profile")
        )
        + "\n    ),"
        for spec in topics
        if spec.get("transport", "dds") == "dds"
    )
    return f'''# Generated by tools/generate_topic_contracts.py. Do not edit.
"""Typed views of the canonical runtime topic catalogue."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class RuntimeTopics:
    """Logical topic names used by Python runtime code."""

{fields}


@dataclass(frozen=True, slots=True)
class TopicSpec:
    """Native DDS binding for one logical topic."""

    topic: str
    dds_topic: str
    message_type: str
    qos_profile: str

    @property
    def idl_type(self) -> str:
        return self.message_type

    @property
    def type_name(self) -> str:
        return self.message_type.rsplit(".", 1)[-1]


TOPICS = RuntimeTopics()

TOPIC_SPECS = {{
{dds_specs}
}}


def topic_spec(topic: str) -> TopicSpec | None:
    """Return the DDS contract for one logical topic."""

    return TOPIC_SPECS.get(str(topic))


def dds_topic_name(topic: str) -> str:
    """Return the DDS wire name, falling back to the standard rt prefix."""

    name = str(topic)
    spec = TOPIC_SPECS.get(name)
    return spec.dds_topic if spec else ("rt" + name if name.startswith("/") else name)
'''


def render_cpp(topics: list[dict[str, Any]]) -> str:
    dds_topics = [spec for spec in topics if spec.get("transport", "dds") == "dds"]
    constants = "\n".join(
        f'''inline constexpr TopicContract {spec["cpp_name"]}{{
    "{spec["topic"]}", "{spec["dds_topic"]}", "{spec["message_type"]}",
    dds::QosProfile::{spec["qos_profile"]}}};'''
        for spec in dds_topics
    )
    array = "\n".join(f"    {spec['cpp_name']}," for spec in dds_topics)
    return f"""// Generated by tools/generate_topic_contracts.py. Do not edit.
#pragma once

#include "transport/dds/profile.hpp"

#include <string_view>

namespace lingtu::message {{

struct TopicContract {{
  std::string_view topic;
  std::string_view dds_topic;
  std::string_view idl_type;
  dds::QosProfile qos_profile;
}};

{constants}

inline constexpr TopicContract kTopicContracts[] = {{
{array}
}};

inline constexpr const TopicContract* find_topic_contract(
    std::string_view topic) noexcept {{
  for (const auto& contract : kTopicContracts) {{
    if (contract.topic == topic) return &contract;
  }}
  return nullptr;
}}

}}  // namespace lingtu::message
"""


def render_idl() -> str:
    declarations = "\n".join((IDL_DIR / f"{domain}.idl").read_text(encoding="utf-8").strip() for domain in IDL_DOMAINS)
    return f"""// Generated by tools/generate_topic_contracts.py. Do not edit.
module lingtu {{
module dds {{

{declarations}

}};
}};
"""


def update(path: Path, content: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == content:
        return False
    if check:
        print(f"stale generated file: {path.relative_to(ROOT)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    topics = load_topics()
    constants = load_constants()
    changed = [
        update(PYTHON_OUTPUT, render_python(topics), check=args.check),
        update(CPP_OUTPUT, render_cpp(topics), check=args.check),
        update(IDL_OUTPUT, render_idl(), check=args.check),
        update(ROOT / "src/message/generated/enums.py", render_python_enums(constants), check=args.check),
        update(ROOT / "src/message/generated/enums.hpp", render_cpp_enums(constants), check=args.check),
        update(ROOT / "src/message/generated/schema.py", render_schema(), check=args.check),
    ]
    return int(args.check and any(changed))


if __name__ == "__main__":
    raise SystemExit(main())
