FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cargo \
    cmake \
    git \
    libatlas-base-dev \
    libboost-all-dev \
    libeigen3-dev \
    libgflags-dev \
    libgl1-mesa-dev \
    libglfw3-dev \
    libglm-dev \
    libgoogle-glog-dev \
    libjpeg-dev \
    libomp-dev \
    libpng-dev \
    libsuitesparse-dev \
    pkg-config \
    python3-colcon-common-extensions \
    python3-rosdep \
    rustc \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN git clone https://github.com/ceres-solver/ceres-solver \
  && cd ceres-solver \
  && git checkout e47a42c2957951c9fafcca9995d9927e15557069 \
  && cmake -S . -B build -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DUSE_CUDA=OFF \
  && cmake --build build -j"$(nproc)" \
  && cmake --install build \
  && rm -rf /root/ceres-solver \
  && ldconfig

RUN git clone https://github.com/koide3/iridescence --recursive \
  && cmake -S iridescence -B iridescence/build -DCMAKE_BUILD_TYPE=Release \
  && cmake --build iridescence/build -j"$(nproc)" \
  && cmake --install iridescence/build \
  && rm -rf /root/iridescence \
  && ldconfig

COPY . /root/ros2_ws/src/direct_visual_lidar_calibration

WORKDIR /root/ros2_ws

RUN rosdep init || true \
  && rosdep update \
  && apt-get update \
  && rosdep install -i --from-paths src --rosdistro humble -y \
  && rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c ". /opt/ros/humble/setup.bash; colcon build"

RUN echo "#!/bin/bash" >> /ros_entrypoint.sh \
  && echo "set -e" >> /ros_entrypoint.sh \
  && echo "source /opt/ros/humble/setup.bash" >> /ros_entrypoint.sh \
  && echo "source /root/ros2_ws/install/setup.bash" >> /ros_entrypoint.sh \
  && echo 'exec "$@"' >> /ros_entrypoint.sh \
  && chmod a+x /ros_entrypoint.sh

WORKDIR /root/ros2_ws/src/direct_visual_lidar_calibration

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    python3-matplotlib \
    python3-numpy \
    python3-opencv \
    python3-pip \
    python3-torch \
    python3-torchvision \
  && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/magicleap/SuperGluePretrainedNetwork /root/SuperGlue
ENV PYTHONPATH=$PYTHONPATH:/root/SuperGlue

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
