"""Simulation and development profile catalog.

These profiles are useful runtime entrypoints, but they are not Thunder product
intent. Keeping them separate avoids mixing deployment product shape with
simulator-specific launch and adapter concerns.
"""

from __future__ import annotations

from typing import Any

from runtime.profiles.catalog.runtime_paths import (
    DEFAULT_GATEWAY_PORT,
    DEFAULT_PLANNING_FRAME_ID,
    _resolve_octoplanner3d_map,
)
from runtime.runtime_interface import TOPICS

SIMULATION_PROFILE_CONFIGS: dict[str, dict[str, Any]] = {
    "sim": dict(
        _desc="MuJoCo simulation",
        _driver_backend="sim",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        # Keep profile execution inside the Module graph. The ROS2 native
        # localPlanner publishes /nav/local_path, but this profile consumes
        # nav.local_planner.local_path, so use the in-process planner here.
        enable_native=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        enable_semantic=True,
        enable_gateway=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "portable_mujoco": dict(
        _desc="Portable no-ROS MuJoCo planning + sensor runtime",
        _driver_backend="sim",
        world="open_field",
        render=False,
        drive_mode="kinematic",
        slam_profile="none",
        detector="sim_scene",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=False,
        enable_gateway=False,
        enable_teleop=False,
        enable_hw=False,
        enable_map_modules=True,
        enable_camera=True,
        use_driver_camera=True,
        use_driver_lidar=True,
        use_driver_imu=True,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=False,
        enable_traversable_frontier=False,
        exploration_backend="none",
        python_autonomy_backend="simple",
        python_path_follower_backend="pid",
        waypoint_threshold=0.35,
        downsample_dist=0.5,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        run_startup_checks=False,
        planner_latency_budget_ms=250,
    ),
    "sim_mujoco_live": dict(
        _desc=("Legacy MuJoCo Module harness for downstream nav/map wiring; not real-equivalent native DDS closure"),
        _driver_backend="sim_endpoint",
        _external_launcher="sim/scripts/mujoco/launch_fastlio2_live.sh",
        _runtime_contract="mujoco_fastlio2_live",
        _runtime_graph_role="host_simulation",
        _real_equivalent=False,
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=False,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_camera=False,
        use_driver_camera=False,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=True,
        enable_traversable_frontier=True,
        exploration_backend="none",
        frontier_safe_distance=0.80,
        frontier_max_dist=25.0,
        frontier_rate=2.0,
        enable_native=False,
        local_planner_allow_direct_track_fallback=True,
        local_planner_ignore_near_field_stop=True,
        local_planner_direct_track_fallback_min_distance_m=0.3,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_mujoco_octo_live": dict(
        _desc=(
            "Legacy MuJoCo Module harness for OctoPlanner3D downstream closure; not real-equivalent native DDS closure"
        ),
        _driver_backend="sim_endpoint",
        _external_launcher="sim/scripts/mujoco/launch_fastlio2_live.sh",
        _runtime_contract="mujoco_fastlio2_live",
        _runtime_graph_role="host_simulation",
        _real_equivalent=False,
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=False,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_camera=False,
        use_driver_camera=False,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=False,
        enable_traversable_frontier=False,
        exploration_backend="none",
        enable_native=False,
        local_planner_allow_direct_track_fallback=False,
        local_planner_ignore_near_field_stop=False,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_nav": dict(
        _desc="No-ROS navigation sim (OctoPlanner3D + C++ local planner when built)",
        _driver_backend="stub",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        scene_xml="sim/worlds/mujoco/building_scene.xml",
        enable_sim_lidar=True,
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=False,
        enable_gateway=True,
        enable_map_modules=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
    ),
    "dev": dict(
        _desc="Test perception & planning without a robot",
        _driver_backend="stub",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=True,
        enable_gateway=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "stub": dict(
        _desc="Framework testing only",
        _driver_backend="stub",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        map_path=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=False,
        enable_gateway=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
}

SIMULATION_ENTRYPOINT_PROFILES = SIMULATION_PROFILE_CONFIGS

SIMULATION_PROFILES = (
    "stub",
    "dev",
    "sim",
    "portable_mujoco",
    "sim_mujoco_live",
    "sim_mujoco_octo_live",
    "sim_nav",
)


def simulation_profile(name: str) -> dict[str, Any]:
    """Return a copy of a simulation or development profile."""

    return dict(SIMULATION_PROFILE_CONFIGS[name])
