"""Simulation and development profile catalog.

These profiles are useful runtime entrypoints, but they are not Thunder product
intent. Keeping them separate avoids mixing deployment product shape with
simulator-specific launch and adapter concerns.
"""

from __future__ import annotations

import os
from typing import Any

from runtime.profiles.catalog.runtime_paths import (
    DEFAULT_GATEWAY_PORT,
    DEFAULT_PLANNING_FRAME_ID,
    _resolve_octoplanner3d_map,
    _resolve_tomogram,
)
from runtime.runtime_interface import TOPICS

SIMULATION_PROFILE_CONFIGS: dict[str, dict[str, Any]] = {
    "sim": dict(
        _desc="MuJoCo simulation",
        _default_robot="sim",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        # Keep profile execution inside the Module graph. The ROS2 native
        # localPlanner publishes /nav/local_path, but this profile consumes
        # nav.local_planner.local_path, so use the in-process planner here.
        enable_native=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        enable_semantic=True,
        enable_gateway=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "portable_mujoco": dict(
        _desc="Portable no-ROS MuJoCo planning + sensor runtime",
        _default_robot="sim",
        world="open_field",
        render=False,
        drive_mode="kinematic",
        slam_profile="none",
        detector="sim_scene",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=False,
        enable_gateway=False,
        enable_teleop=False,
        enable_device_manager=False,
        enable_map_modules=True,
        enable_camera=True,
        use_driver_camera=True,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=False,
        enable_traversable_frontier=False,
        exploration_backend="none",
        python_autonomy_backend="simple",
        python_path_follower_backend="pid",
        waypoint_threshold=0.35,
        downsample_dist=0.5,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        run_startup_checks=False,
        manage_external_services=False,
        planner_latency_budget_ms=250,
    ),
    "sim_mujoco_live": dict(
        _desc="MuJoCo raw MID-360 + Fast-LIO live simulation",
        _default_robot="sim_endpoint",
        _external_launcher="sim/scripts/mujoco/launch_fastlio2_live.sh",
        _runtime_contract="mujoco_fastlio2_live",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=False,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_camera=False,
        use_driver_camera=False,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=True,
        enable_traversable_frontier=True,
        exploration_backend="none",
        frontier_safe_distance=0.80,
        frontier_max_dist=25.0,
        frontier_rate=2.0,
        enable_native=False,
        local_planner_allow_direct_track_fallback=True,
        local_planner_ignore_near_field_stop=True,
        local_planner_direct_track_fallback_min_distance_m=0.3,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        manage_external_services=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_mujoco_octo_live": dict(
        _desc="MuJoCo Fast-LIO + OctoPlanner3D closed-loop simulation",
        _default_robot="sim_endpoint",
        _external_launcher="sim/scripts/mujoco/launch_fastlio2_live.sh",
        _runtime_contract="mujoco_fastlio2_live",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=False,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_camera=False,
        use_driver_camera=False,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=False,
        enable_traversable_frontier=False,
        exploration_backend="none",
        enable_native=False,
        local_planner_allow_direct_track_fallback=False,
        local_planner_ignore_near_field_stop=False,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        manage_external_services=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_mujoco_pct_live": dict(
        _desc="MuJoCo Fast-LIO + PCT closed-loop simulation",
        _default_robot="sim_endpoint",
        _external_launcher="sim/scripts/mujoco/launch_fastlio2_live.sh",
        _runtime_contract="mujoco_fastlio2_live",
        slam_profile="none",
        llm="mock",
        planner="pct",
        planner_backend="pct",
        tomogram=_resolve_tomogram(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=False,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_camera=False,
        use_driver_camera=False,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=False,
        enable_traversable_frontier=False,
        exploration_backend="none",
        enable_native=False,
        local_planner_allow_direct_track_fallback=False,
        local_planner_ignore_near_field_stop=False,
        path_follower_goal_tolerance=0.12,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        manage_external_services=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_gazebo": dict(
        _desc="Gazebo/GZ external simulation with LingTu Module navigation",
        _default_robot="sim_endpoint",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=True,
        enable_gateway=True,
        enable_map_modules=True,
        enable_camera=True,
        use_driver_camera=True,
        cloud_topic=TOPICS.map_cloud,
        # Gazebo raw topics stay outside the Module graph. The script-level
        # Gazebo endpoint runtime injects normalized streams into
        # SimEndpointDriverModule, while planning and App/Web goal contracts
        # stay in map frame.
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        # The Gazebo profile is ROS-native at the simulator boundary, while
        # planning/tracking stay in the Module graph so /nav/local_path cannot
        # disappear into an unbridged external ROS2 process.
        enable_native=False,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_industrial": dict(
        _desc="Engineering Gazebo industrial-yard simulation",
        _default_robot="sim_endpoint",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_semantic=True,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_camera=True,
        use_driver_camera=True,
        cloud_topic=TOPICS.map_cloud,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        enable_frontier=True,
        exploration_backend="none",
        frontier_safe_distance=0.80,
        frontier_max_dist=20.0,
        frontier_rate=2.0,
        enable_native=False,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        manage_external_services=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_cmu_tare": dict(
        _desc="CMU Unity + external TARE simulation",
        _default_robot="sim_endpoint",
        _external_launcher="sim/scripts/launch_cmu_unity_lingtu_runtime.sh",
        _runtime_contract="cmu_unity_external",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=os.environ.get("LINGTU_CMU_OCTOMAP", _resolve_octoplanner3d_map()),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy=os.environ.get("LINGTU_CMU_PLAN_SAFETY_POLICY", "reject"),
        fallback_planner_name="",
        safe_goal_tolerance=0.4,
        waypoint_threshold=0.45,
        final_waypoint_threshold=0.35,
        stuck_timeout=25.0,
        stuck_dist_thre=0.08,
        downsample_dist=0.6,
        path_follower_goal_tolerance=0.35,
        local_planner_allow_direct_track_fallback=True,
        local_planner_ignore_near_field_stop=True,
        local_planner_direct_track_fallback_min_distance_m=0.3,
        enable_native=False,
        enable_semantic=False,
        enable_gateway=True,
        enable_teleop=False,
        enable_map_modules=True,
        enable_nav_out=False,
        exploration_backend="tare_external",
        exploration_auto_start=True,
        prefer_path_strategy=True,
        path_start_tolerance_m=1.5,
        path_goal_min_distance_m=1.0,
        path_goal_spacing_m=0.75,
        tare_fallback_timeout_s=180.0,
        allow_direct_goal_fallback=True,
        direct_goal_fallback_on_planner_failure=True,
        accept_partial_goal_progress=True,
        partial_goal_repeat_ignore_window_s=5.0,
        external_strategy_path_control=False,
        external_strategy_start_tolerance_m=1.5,
        planning_frame_id=DEFAULT_PLANNING_FRAME_ID,
        latch_stop_signal=False,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
        run_startup_checks=False,
        manage_external_services=False,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "sim_nav": dict(
        _desc="No-ROS navigation sim (OctoPlanner3D + C++ local planner when built)",
        _default_robot="stub",
        slam_profile="none",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        scene_xml="sim/worlds/mujoco/building_scene.xml",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=False,
        enable_gateway=True,
        enable_map_modules=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
        python_autonomy_backend="nanobind",
        python_path_follower_backend="nav_kernel",
    ),
    "dev": dict(
        _desc="Test perception & planning without a robot",
        _default_robot="stub",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=True,
        enable_gateway=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
    "stub": dict(
        _desc="Framework testing only",
        _default_robot="stub",
        llm="mock",
        planner="octoplanner3d",
        planner_backend="octoplanner3d",
        tomogram=_resolve_octoplanner3d_map(),
        map_artifact_gate_required=False,
        octoplanner3d_timeout_s=30.0,
        plan_safety_policy="reject",
        fallback_planner_name="",
        enable_native=False,
        enable_semantic=False,
        enable_gateway=True,
        gateway_port=DEFAULT_GATEWAY_PORT,
    ),
}

SIMULATION_ENTRYPOINT_PROFILES = SIMULATION_PROFILE_CONFIGS

SIMULATION_PROFILES = (
    "stub",
    "dev",
    "sim",
    "portable_mujoco",
    "sim_mujoco_live",
    "sim_mujoco_octo_live",
    "sim_mujoco_pct_live",
    "sim_gazebo",
    "sim_industrial",
    "sim_cmu_tare",
    "sim_nav",
)



def simulation_profile(name: str) -> dict[str, Any]:
    """Return a copy of a simulation or development profile."""

    return dict(SIMULATION_PROFILE_CONFIGS[name])
